### ISSUE TITLE
importing ALAC files to job list takes too long

### ISSUE THREAD

**Issue by gdsa32** [enzo1982/freac#10]
I am using fre:ac v1.1 alpha 20180306 32bit, on Windows 10 64bit.

While importing a group of ALAC/M4A files to the job list, I noticed this takes too much time on my not so slow Core i5 with 8GB RAM computer.

So I made some tests importing the same album (12 tracks) in different formats to the job list.
In MP3, AAC/M4A or FLAC formats, it took less than 1 second to import the album.
In ALAC/M4A format it took 16 seconds to import the same album.

I'm not sure if this a bug, inefficient code or simply a characteristic of the codec/format.
But I thought I should report it, regardless. Please let me know if additional information is needed for o proper investigation on the issue.

**Comment by enzo1982** [comment]
Yes, this is a known issue.

fre:ac uses avconv to decode ALAC files and that tool does not report the full length when decoding only the header. So what fre:ac does is decode the whole file when adding the track to the joblist in order to find out the track length.

This takes longer, but allows fre:ac to display the track length in the joblist.

I plan to eventually implement a Core Audio decoder component able to decode ALAC. Such a component would not have this limitation and fre:ac would only fall back to avconv if Core Audio is not available.

**Comment by gdsa32** [comment]
OK. Thanks.

**Comment by enzo1982** [comment]
fre:ac 1.1.6 now comes with a native ALAC decoder which fixes the slow loading of ALAC files. Closing this issue.
