### ISSUE TITLE
MP3 size and duration differs when using "SuperFast mode"

### ISSUE THREAD

**Issue by creopard** [enzo1982/freac#103]
**Describe the bug**
Encoding several .wav files to one .mp3 file (= checkbox "encode to a single file") using "SuperFast mode" in conjunction with the lame MP3 encoder seems to have an impact on the file size as well on the duration. 
3rd party mp3-validation software complain about the duration and the actual duration of the file (see screenshot as an example)

**To Reproduce**
1. Queue several .wav files in freac
2. **Enable** "SuperFast mode": Encode to one .mp3 file using the checkbox "encode to a single file"
3. **Disable** "SuperFast mode": Encode to one .mp3 file using the checkbox "encode to a single file"
4. Compare the two resulting .mp3 files with each other. They will differ in file size and duration.
The "SuperFast mode" encoded mp3 will have a smaler filesize and a smaler calculated(?) duration.

**Expected behavior**
The file sizes and duration should match

**Screenshots**
Screenshot from the [fakinthefunk software](https://fakinthefunk.net):
![comparison](https://user-images.githubusercontent.com/14175483/78831106-6100ba80-79e9-11ea-9b07-6ed4cb8d0c0c.jpg)

**System (please complete the following information)**
 - freac version 1.1 (x86-64)
 - OS: Win10 1909
 - CPU: Ryzen 5 1600
 - RAM: 16 GB

**Comment by enzo1982** [comment]
This is due to the bitstream repacking happening in SuperFast mode. Files created with SuperFast mode will have less padding bytes in the MP3 frames. You will see this only in CBR mode and it does not affect quality.

It does, however, affect the duration displayed by software ignoring the LAME header (Fakin' The Funk displays both, the calculated duration in the _Duration_ field and the duration advertised in the LAME header in the _Actual duration_ field), so this actually is a valid concern.

Fortunately, fixing this is simple. Here is an updated boca_encoder_lame.1.0.dll that you can use for testing: [boca_encoder_lame.1.0.zip](https://github.com/enzo1982/freac/files/4453117/boca_encoder_lame.1.0.zip) (just replace the corresponding file in the boca folder with the new version)

The fix will be part of the upcoming fre:ac 1.1.1 update.

**Comment by creopard** [comment]
Great work!
Thank you, the new boca_encoder_lame.1.0.dll fixed the duration issue indeed!

**Comment by enzo1982** [comment]
fre:ac 1.1.1 is now available with the fix for this issue. Closing this ticket.
