### ISSUE TITLE
cue files still read after disabling it

### ISSUE THREAD

**Issue by har2121** [enzo1982/freac#105]
**Describe the bug**

If I choose a directory to convert wich containes cue files, freac reads the cue files. When I start the convert freac comes with the warning that there are files with the same name and asks to overwrite them. If I do so, only the last file named in the cue file remains in the converted files.
I disabled in Options, Info tags, Different, Cue sheets, but stil freac reads the cue files.

**To Reproduce**
3. See error

I've described this above.

**Expected behavior**

I expected that the cue files are not read and only the only FLAC file shoud be converted to MP3 file.

**Screenshots**

**System (please complete the following information)**
 - OS: Windows 8.1, newest build
 - CPU: Intel Core i7
 - RAM: 8 GB

**Additional context**

**Comment by enzo1982** [comment]
The cue sheet options on the tags configuration page only apply to cue sheets embedded in tags, not separate .cue files. There currently is no option to disable reading .cue files when adding a folder containing them.

However, reading the .cue files does not appear to be the issue here at all. The overwrite confirmation dialog comes up before starting a conversion when multiple tracks in the joblist would generate the same output file name according to the configured file name pattern.

Please check the output file name pattern on the first page of the configuration dialog. If it says e.g. `<artist> - <title>`, but the artist is the same for all tracks and titles are not available (showing _unknown title_ in the joblist), then all files would have the same name and if you confirm the overwrite dialog, only the last file converted would end up in the output folder.

There are two different options to resolve this:

1. Enable the _Append sequential numbers to otherwise identical filenames_ option (below the output filename pattern in the configuration dialog).
2. Enter an output filename pattern that will resolve to a different filename for each track, e.g. by including the `<track>` placeholder.

**Comment by har2121** [comment]
Thank you for your quick answer! I have it running OK now!
