### ISSUE TITLE
Problem with lengh of audio files with LAME MP3

### ISSUE THREAD

**Issue by MadKeyboard** [enzo1982/freac#107]
**Describe the bug**
To begin, sorry for my bad english, i'm french :) I'll try to be explicite !
So, I'm a musicien and I'm happy I can use fre:ac to transfert audio files from my composition or other.
But I have a major problème using LAME MP3 : the lengh of the audio while converting from .wav format to mp3 format is not correct ! I always get about 50ms of silence add at the beginning of my mp3 file, so I can't use it to send audios to my co-workers so they can use it for music (50ms is very very much for music ! 5ms would be ok but not much).

I've tried changing every parameters of the encoder, and I checked every parameters of the app, nothing to do.
I noticed when I turn VBR quality to low, the delay get's up to about 200ms.
I've tried CBR and ABR, with different quality, same result.

**To Reproduce**
You can't without a audio workstation !
I did tests with screenshot to show you (see below)

**Expected behavior**
I've never seen this problem in any converter, so I'm a bit surprised ! Even in software using the LAME MP3. Is there anything someone can do ?

**Screenshots**
<a href="https://ibb.co/QvzCZ0j"><img src="https://i.ibb.co/QvzCZ0j/Screenshot-freac-problem.png" alt="Screenshot-freac-problem" border="0"></a>

**System (please complete the following information)**
 - WINDOWS 10 pro
 - Intel Core i5
 - RAM 8 GB

**Comment by enzo1982** [comment]
Hi, this is not an issue with fre:ac, but with Ableton Live (and most other DAWs, actually).

What you are seeing is called codec delay and is an inherent aspect of the MP3 format. It needs to be compensated for by the decoding application. To make that possible, the encoding application writes delay information to the MP3 file (fre:ac does that in the form of a Xing VBR/LAME Info header). The decoding application then uses that information to compensate the delay (which Ableton fails to do correctly).

I know this is a problem with most DAWs. I work for another DAW maker in my day job and added support for sample-exact MP3 decoding there only last year.

In any case, this is not a bug in fre:ac. All the information needed to compensate the MP3 delay is there in the files. You can verify this by converting the MP3 to WAV or FLAC with fre:ac or another application supporting gapless MP3 decoding and importing the resulting file file into Ableton. The delay should be gone.

In general, MP3 is not a suitable exchange format for audio production workflows due to these issues with various software. Better use a lossless format like FLAC instead. It's also supported by Ableton and does not have these delay issues.

**Comment by MadKeyboard** [comment]
Hello !! Thanks a lot for your explainations !!
Was trying to save cloud space with MP3, the only compressed format eccepted in Ableton...
Well, let's do FLAC :)
