### ISSUE TITLE
Update to v1.1.1 did not retain encoder preferences

### ISSUE THREAD

**Issue by JLGF1** [enzo1982/freac#108]
**Describe the bug**
My default encoder is FLAC. After I was prompted to upgrade, I proceeded to encode a few CD's before noticing that my default encoder had changed to the first in the encoder list (MA4?).

ie sticky prefs setting was not read in.

**To Reproduce**
Update from pre v1.1.1 with default encoder of FLAC.
Check the default encoder.

**Expected behavior**
Default encoder from previous version should be retained...
-or-
A dialog notice to check it and reset it to desired default.

**Screenshots**

![freeAC](https://user-images.githubusercontent.com/64571200/80670070-fa187380-8a73-11ea-97a4-4770674e379b.JPG)

**System (please complete the following information)**
 - OS: Windows-10
 - CPU: AMD Ryzen-3
 - RAM: 8GB

**Additional context**

**Comment by enzo1982** [comment]
Thank you for reporting this!

I just made two changes to improve the situation. First, fre:ac will try to keep the previously selected encoder selected when upgrading from a 1.0.x release. This should work in 99.9% of cases. Where it won't work is when the previously selected encoder was Bonk, which is no longer included with fre:ac 1.1, or when users added the BladeEnc MP3 encoder to their installation (as this changes the indices that are used to identify encoders in fre:ac 1.0.x).

The second change is defaulting to the LAME MP3 encoder instead of the first in the list in case the selected encoder is not available.

These changes will be part of fre:ac 1.1.2.

**Comment by enzo1982** [comment]
fre:ac 1.1.2 is available now. Closing this issue.
