### ISSUE TITLE
a way to disable writing program name into tracks metadata

### ISSUE THREAD

**Issue by vnuchentos** [enzo1982/freac#118]
> encoder         : fre:ac v1.1
![image](https://user-images.githubusercontent.com/66915883/84598879-7e815300-ae76-11ea-999b-e33544768899.png)

**Comment by enzo1982** [comment]
fre:ac writes its name and version to the _"Encoder settings"_ field. This is a technical field and not normally displayed to the user by player software.

The rationale is to allow identifying files encoded with specific versions of a program, e.g. to be able to find files that need re-encoding if a specific software version turns out to contain a bug affecting file integrity. See the corresponding Vorbis Comment fields proposal for reference: https://wiki.xiph.org/index.php?title=VorbisComment#ENCODER

Almost all tag formats specify dedicated fields for this and it's generally considered good practice to store this information. FFmpeg, for example, does the same - also without offering an option to turn it off btw.

Also note that this field is distinct from the _"Encoded by"_ field which may contain the name of the person who did the encoding.

So I don't really see a reason to add an option to suppress this field. It's a technical field that is not usually displayed to the user. It's basically like the vendor string in Vorbis Comment tags or the software field in a LAME info tag (which also cannot be suppressed), just one level higher, specifying the tool instead of the codec.
