### ISSUE TITLE
Files are tagged 01-trackname.mp3.wav when "Keep ripped Wave files" is selected

### ISSUE THREAD

**Issue by Peppernrino** [enzo1982/freac#135]
**Describe the bug**
Files are tagged 01-trackname.mp3.wav when "Keep ripped Wave files" is selected.

**To Reproduce**
1. Extract CD audio with option selected.
2. Files are tagged as such.

**Expected behavior**
I was hoping it wouldn't have the ".mp3" part in the Wave files.

**System (please complete the following information)**
 - OS: Windows 8.1
 - CPU: Ryzen 1600X
 - RAM: 16GB

**Comment by enzo1982** [comment]
This is intentional. The _"Keep ripped Wave files"_ option is not meant to output .wav files for archival. The `.mp3` part is there so it won't interfere with .wav files with the same names that may already be present in the output folder.

To get what you want, please use the _meh! - multi encoder hub_ configured with LAME and Wave as the output encoders.

**Comment by Peppernrino** [comment]
Ah! Consider me corrected. Thanks again! Gonna have to check out this meh!... sounds useful.
