### ISSUE TITLE
Unable to Correctly Detect Running Time/Length of Some Mp3 Audio

### ISSUE THREAD

**Issue by hairycactus** [enzo1982/freac#138]
**Issue:** fre:ac is unable to correctly detect the running time/length of certain input MP3 audio files.

Sample [MP3 file (podcast)](https://omny.fm/shows/st-bt/on-covid-19-airborne-transmission-and-immunity-hea.mp3) for testing

- **Actual Running Time:** 18:22 min
- **Detected Running Time:** 00:35 min

For the above sample file, fre:ac is able to see, play & process only the first 35 secs of the above input MP3 audio.

**What I Did:**  
Convert 128 kbps MP3 to 64 kbps (CBR) MP3 using LAME MP3 Encoder. 

**Output File:**  
MP3 file is only 35 secs long & ~315 KB in filesize. No silence or audio delay introduced.

**Affects:** fre:ac v1.1.2b x64 (09 Jul 20) & older versions
**System:** Windows 10 x64

Audio players & other audio converters that I tried (eg. LameXP, ShanaEncoder, etc.) all correctly detect & play/convert the full length of the MP3 file. As such, I don't think the issue seen in fre:ac is caused by the LAME Encoder.

Not sure if this is related, but another user mentions about fre:ac being unable to detect audio length, & encountered silence/ audio delay inserted to the beginning of output MP3 file (#107):
https://github.com/enzo1982/freac/issues/107

**Comment by enzo1982** [comment]
Thank you for reporting this and for including the link to the file! This made it possible to identify the problem quickly.

There is an issue with the chapter tags in the podcast file. The file contains an ID3v2.3 tag, but the sub-frames in the chapter frames have ID3v2.4 frame headers. Now the difference between an ID3v2.3 and a 2.4 frame header is that the frame size is specified in a different format (raw integer in 2.3, unsynchronized integer in 2.4). Thus, the tag reader assumes the wrong length for the sub-frames and is thrown off.

This will show up only with very long chapter names (like in the file at hand). Specifically, the size of a chapter sub-frame must exceed 127 bytes - only then there's a difference between raw and unsynchronized integers. In this case it's 140 bytes for the first chapter title (70 characters encoded as a UTF-16 Unicode string).

The tag reader failing to read the chapters leaves fre:ac with only one chapter for the file and that first chapter is 35 seconds long.

This will be fixed in the next release by ignoring broken chapters (chapter information will be discarded if the number of chapters read does not match the number announced in the chapter TOC frame). Until then, you can work around the issue by disabling reading of chapters in fre:ac's configuration dialog (_Tags_->_Other_->_Read chapters from files_).

You won't see this issue with most other software, because most programs do not support ID3v2 chapter tags at all and just skip them completely.

The actual invalid tag data seems to come from a bug in the software used for authoring the podcast (which appears to be OmnyStudio). In case you are the author of that podcast and are an OmnyStudio customer, you might want to report the issue to them. I'll also send them a friendly mail if I can find contact info on their site, but a support ticket opened by an actual customer often is more effective.

**Comment by enzo1982** [comment]
The fix for handling invalid chapter data is now available as part of fre:ac 1.1.3.
