### ISSUE TITLE
Freac 1.1.2b can't open a specific cue file that CUEtools 2.1.7 can

### ISSUE THREAD

**Issue by masterrite** [enzo1982/freac#139]
I have this cue file that I want to use to convert my ripped track but freac 1.1.2b and VLC can't read it. CUEtools 2.1.7 can, however. I suspect it has to do with the Chinese characters inside. Opening the cue file in notepad++ shows that it's just a normal cue file, and has no difference from a random cue file generated within freac. I wonder if you can pinpoint the problem and find a solution to it?

I'm using Windows 10 v2004.

I'm attaching the cue file. [Everything in the World cue.zip](https://github.com/enzo1982/freac/files/4976302/Everything.in.the.World.cue.zip) For the cue file and the track's wav file see [here](https://1drv.ms/u/s!Arg3ath-9zQRgqF4yfDrS92q3WsIXg?e=Haxd44).

Thanks!

**Comment by enzo1982** [comment]
There are two issues with the cue file.

First, it references the wrong file, `曲婉婷 - Everything in the World.wav` instead of just `Everything in the World.wav`. So fre:ac simply fails to find the file referenced in the cue sheet.

Second, the cue sheet uses UTF-8 encoding, but has no byte order mark (BOM) at the start. The BOM is a non-visible byte sequence that identifies files as UTF-8.

fre:ac currently supports only UTF-8 with BOM or ISO-8859-1 (Western European) as cue sheet encodings. This means it would open the cue sheet if the file name was correct, but won't display the Chinese titles correctly. In response to this issue, however, the next release will add support for UTF-8 without BOM and for cue sheets encoded in the system codepage (on Windows systems).

Here's a fixed cue sheet that will open in fre:ac 1.1.2 and display the Chinese characters correctly: [Everything in the World.zip](https://github.com/enzo1982/freac/files/4976865/Everything.in.the.World.zip)

**Comment by masterrite** [comment]
Thank you!
