### ISSUE TITLE
missing boca.h

### ISSUE THREAD

**Issue by tjlynchny** [enzo1982/freac#14]
When I try to 'make' the application, it halts with:

In file included from src/cddb/cddb.cpp:13:0:
~/src/freac/include/cddb/cddb.h:16:10: fatal error: boca.h: No such file or directory
 #include <boca.h>

Tried googling for boca.h, but no luck finding it.

Running an up to date Kubuntu 17.10

**Comment by enzo1982** [comment]
Hi, as explained in the [Readme.md](https://github.com/enzo1982/freac#compiling) file, fre:ac depends on the [smooth Class Library](https://github.com/enzo1982/smooth/) and the [BoCA audio component framework](https://github.com/enzo1982/boca/). Please build and install those first.

Also, development packages for the following libraries need to be installed in order to build smooth, BoCA and fre:ac:

    For the smooth Class Library: libbz2, libcurl, libfribidi, libgtk+3.0, libjpeg, libxml2
    For the BoCA component framework: libasound2, libcdio, libcdio-paranoia, libexpat, liburiparser
    For fre:ac itself: libudev

When the dependencies are met, run make followed by sudo make install for smooth, BoCA and fre:ac respectively.

You should then be able to run fre:ac using /usr/local/bin/freac and the command line interface using /usr/local/bin/freaccmd.

**Comment by enzo1982** [comment]
Please close this ticket if my above comment solved this for you. If there is no reaction, I will close it in two weeks.
