### ISSUE TITLE
Adding tags to wav-files crashes them

### ISSUE THREAD

**Issue by Victor-Ch** [enzo1982/freac#148]
When i try to add some tags like "Title" or "Artist" to a wav-file (in the tag editor - "Tags" tab -> "Files") the program does it. Then i successfully save the edited wav-file. And after that the file becomes unreadable(unplayable) anymore with the freac and other applications.
If i try to open the file again with freac (in the tag editor or adding in the job list) - error window popups:
"Unable to open file: test.wav
Error: Unknown file type"

I guess it's a bug and should be fixed.

Free AC version: v1.1.2b (x86-64)
OS: Windows 7 64bit

**Comment by enzo1982** [comment]
Thank you for reporting this and sorry for not answering earlier! I tried to reproduce this back then, but failed, and then forgot about it instead of taking a closer look.

However, during development for fre:ac 1.1.5 I came across this exact issue and fixed it. So the problem should be fixed in fre:ac 1.1.5 which adds support for updating tags in WAV files.

If you're still around here, please verify and close the issue. Otherwise I will close this soon.
