### ISSUE TITLE
Drag & Drop Crash

### ISSUE THREAD

**Issue by Nighted** [enzo1982/freac#15]
The title says it all, 1.1 (20180710) crashes when attempting to drop files for processing. D:

Will revert to previous alpha.

Nice that I could easily change the icons if the program were usable. ;)

Thanks

P.S.

As a matter of fact, adding files in any way crashes the program. >:(

**Comment by enzo1982** [comment]
Thank you for your report! But unfortunately, the title does not say it all in this case.

I tried to reproduce the issue by adding a bunch of MP3 files by drag & drop on macOS, Windows and Linux and it is working just fine for me.

Thus I need more information about your specific case in order to analyze and fix the issue:

1. What operating system and system version do you use?
2. What's your hardware? (might be relevant if you are using an older CPU)
3. Are you using the 32 or 64 bit version of fre:ac?
4. What type of files are you trying to add? (MP3, FLAC, Ogg, M4A, ...)
5. Please provide one of the files as an example. (either post it here, post a download link or send it to support@freac.org)

Thanks in advance!

**Comment by Nighted** [comment]
I've tried other files, flac, mp3 etc. with no problems. 

Mp3tag fixes the problem when altering the tag, but when transcoding in fre-ac (previous alpha 1.1 (20180306)) and adding to the new build, the crash occurs: an immediate exit of the program. 

Whatever it is, bad bits/offset, Mp3tag corrects it, fre-ac copies it over to the transcoded file.
This does not occur in the previous alpha. Both of the new builds exhibit this behavior regardless of bitness.

Here you can find the problematic file:

http://rss.gcnlive.com/americanuckRadio/download.php?filename=2018-07-07_americanuckradio0707181.mp3

**Comment by wkremser** [comment]
i tried it with flac files that freac created ripping cds.
 
these flac files were created on linux and in a second batch these files get converted from flac to mp3 on my mac system.

so nothing else involved except freac.

**Comment by enzo1982** [comment]
OK, I identified the crash bug. I was a bad evaluation of a return value deep in the class library used by fre:ac. It's triggered by PNG images embedded in the file's tags.

Here's a fixed version of the smooth.dll for the x64 Windows version: [smooth-0.8.74.0-pre2a-windows-x64.zip](https://github.com/enzo1982/freac/files/2190068/smooth-0.8.74.0-pre2a-windows-x64.zip)

Please try if it fixes the issue for you.

@wkremser: I will check if the FLAC issue on macOS might be caused by the same bug and provide an updated version here in that case. It would be great if you could send me one of your FLAC files, though, to aid my analysis.

In any case, I will package a new alpha release in a few days to fix this issue with embedded PNGs.

**Comment by Nighted** [comment]
Yep, this does the trick for me. Thanks for the quick fix! Living on the bleeding edge! lol

**Comment by enzo1982** [comment]
Thanks for confirming the fix so quickly!

@wkremser: The FLAC issue seems to be something else. I can reproduce it now. No need to send a file. I'll report back when I have a solution.

**Comment by Nighted** [comment]
No, THANK YOU! Still waiting for an optimized LAME encoder. I tested the others a few months ago and was blown away.

**Comment by enzo1982** [comment]
@wkremser: Here's an update for the macOS version of fre:ac fixing the FLAC issue: [freac-1.1-alpha-20180710a-macosx.dmg](https://freac.org/updates/freac-1.1-alpha-20180710a-macosx.dmg) This was caused by an issue with my build system leading to the included FLAC library not loading on most systems. This affected only the macOS version. Please try if the update fixes the issue.

@Nighted: A new preview of the SuperFast version will be available soon including the SuperFast LAME encoder.

**Comment by wkremser** [comment]
The new macOS version works like a charm again :)

**Comment by Nighted** [comment]
@enzo1982: Thanks brother! :D
