### ISSUE TITLE
Opus Encoder embedded Chapter Info is wrong (too short)

### ISSUE THREAD

**Issue by 5andr0** [enzo1982/freac#150]
I'm converting an m4a file with embedded chapters to an opus output.
The embedded chapters in the resulting opus file are always too short.
I tried it with multiple different m4a files and all sorts of settings and even older versions of fre:ac, all resulting in wrong embedded chapter tags.
It works fine with other encoders like ogg vorbis for example.

The generated cue file is correct:
```
  TRACK 01 AUDIO
    TITLE "Chapter 1"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Chapter 2"
    INDEX 01 00:10:16
  TRACK 03 AUDIO
    TITLE "Chapter 3"
    INDEX 01 02:21:20
  TRACK 04 AUDIO
    TITLE "Chapter 4"
    INDEX 01 07:29:05
  TRACK 05 AUDIO
    TITLE "Chapter 5"
    INDEX 01 28:02:42
  TRACK 06 AUDIO
    TITLE "Chapter 6"
    INDEX 01 32:31:58
  TRACK 07 AUDIO
    TITLE "Chapter 7"
    INDEX 01 37:11:39
  TRACK 08 AUDIO
    TITLE "Chapter 8"
    INDEX 01 43:25:24
  TRACK 09 AUDIO
    TITLE "Chapter 9"
    INDEX 01 51:22:16
  TRACK 10 AUDIO
    TITLE "Chapter 10"
    INDEX 01 55:13:53
```

MetaData extracted from the opus file:
```
CHAPTER001=00:00:00.000
CHAPTER001NAME=Chapter 1
CHAPTER002=00:00:09.387
CHAPTER002NAME=Chapter 2
CHAPTER003=00:02:09.792
CHAPTER003NAME=Chapter 3
CHAPTER004=00:06:52.587
CHAPTER004NAME=Chapter 4
CHAPTER005=00:25:45.856
CHAPTER005NAME=Chapter 5
CHAPTER006=00:29:53.195
CHAPTER006NAME=Chapter 6
CHAPTER007=00:34:10.219
CHAPTER007NAME=Chapter 7
CHAPTER008=00:39:53.642
CHAPTER008NAME=Chapter 8
CHAPTER009=00:47:11.787
CHAPTER009NAME=Chapter 9
CHAPTER010=00:50:44.480
CHAPTER010NAME=Chapter 10
```

Tested on linux and windows

**Comment by enzo1982** [comment]
Thank you for reporting this!

I can confirm it's a bug and it's related to Opus files always being encoded at 48 kHz. When the source material has a different sample rate, like 44.1 kHz in this case, the chapter lengths are calculated based on the wrong sample rate.

I'm working on a fix, but getting this right in all cases turned out to be more difficult than expected. So fixing this and verifying the fix in all possible situations will take a few more days.

**Comment by 5andr0** [comment]
@enzo1982 Thanks for fixing this! Really like this program, but freaccmd is giving me a hard time.
Freaccmd is overwriting almost every setting (including encoder settings) from the config, which leaves the --config option quite useless. But without the preconfigured config, there are not enough parameters to configure.

Wouldn't it be better to just pass the --config and only overwrite settings if other parameters are used? Even the default encoder could be read from the config, don't overwrite this with lame-mp3.

Let me know when you fixed it and i'll leave a donation!

**Comment by enzo1982** [comment]
fre:ac 1.1.3 is available now and should fix the chapter offset issue.

I also like your idea to change the behavior of freaccmd's --config option. Created a separate ticket for this: #158

**Comment by rbqbjyur** [comment]
Hi,

Seems fre:ac 1.1.3 is causing issues with chapter info when encoding to single file (either from .m4b or multiple .mp3's) to opus.
Wasn't occuring prior to 1.1.3.

The chapters are out of order, and overlapping

Am getting the below order (via mediainfo)
```
Menu
03:22:49.463                             : Chapter 6
08:19:34.437                             : Chapter 15 / Chapter 5
00:00:09.451                             : Chapter 3
02:34:37.295                             : Chapter 1
04:10:50.550                             : Chapter 10
08:20:09.717                             : Chapter 16 / Chapter 7
04:13:14.093                             : Chapter 4 / Chapter 8
00:59:42.598                             : Chapter 14
```

opusinfo gives below;

```
Encoded with libopus 1.3.1
User comments section follows...
	CHAPTER012NAME=Chapter 12
	CHAPTER002NAME=Chapter 2
	DATE=1950
	CHAPTER009NAME=Chapter 9
	CHAPTER013NAME=Chapter 13
	CHAPTER011NAME=Chapter 11
	ALBUMARTIST=Author
	CHAPTER008=03:22:49.463
	CHAPTER006NAME=Chapter 6
	CHAPTER015=08:19:34.437
	CHAPTER015NAME=Chapter 15
	ALBUM=Book
	CHAPTER005NAME=Chapter 5
	CHAPTER003=00:08:28.287
	CHAPTER004=00:56:36.927
	CHAPTER001=00:00:00.000
	COMMENT=Read by Narrator
	TITLE=Book
	CHAPTER002=00:00:09.451
	CHAPTER003NAME=Chapter 3
	CHAPTER014=07:20:26.493
	CHAPTER007=02:34:37.295
	CHAPTER001NAME=Chapter 1
	CHAPTER006=01:46:00.934
	ARTIST=Author
	CHAPTER010=04:10:50.550
	CHAPTER010NAME=Chapter 10
	CHAPTER012=05:20:28.365
	CHAPTER013=06:18:01.197
	CHAPTER009=03:24:38.958
	CHAPTER016=08:20:09.717
	CHAPTER016NAME=Chapter 16
	CHAPTER007NAME=Chapter 7
	CHAPTER011=04:13:14.093
	CHAPTER004NAME=Chapter 4
	CHAPTER008NAME=Chapter 8
	CHAPTER005=00:59:42.598
	CHAPTER014NAME=Chapter 14
```
Seems the metadata is fine, but the chapters are out of order?
Seems it's not being saved in the expected order of chapter time followed by same chapter name i.e.
```
	CHAPTER001=00:00:00.000
	CHAPTER001NAME=Chapter 1
```

**Comment by enzo1982** [comment]
This looks very strange. The chapter offsets seem to be wrong as well, unless most of your chapters are several hours long.

However, I cannot reproduce this issue with fre:ac 1.1.3. Also, the way fre:ac writes the chapters, it's guaranteed that they come in ascending order and after any other metadata.

That Opus file is probably damaged. It came out of fre:ac directly like this? Or did you process it in some way afterwards?

What platform are you on and what version of fre:ac are you using (Snap, Flatpak, AppImage, Windows Store version, PortableApps.com version, Windows installer version, ...)?

**Comment by rbqbjyur** [comment]
Am using the Flatpak version on Fedora.

Some of the chapters are from 45 - 90 mins long, none would be several hours.

I did use MusicBrainz Picard to mass change Author, and apply Album Art. But other than that no, this is straight from fre:ac.

Just re-ran using same source .mp3s. Came out fine. Re-edited with MusicBrainz, still fine.

My apologies, not sure what caused this.
It did seem to only affect a small portion of the audiobooks I was converting - wasn't consistent.

Will redo the affected ones again tomorrow, and will report back if all well or any issues.

**Comment by rbqbjyur** [comment]
My apologies, I went and re-did all affected files. 100% of them came out perfect.

I then edited Title, Album, and Author via MusicBrainz Picard and they came out with their chapter info messed up (not all of them).

So nothing to do with fre:ac - my bad.

That said, while doing this I noticed that those converted from very long mp3's seem to get shortened (single mp3 at 32.5 hours went to opus with 7.5 hours) - but will open up a separate issue for that.

**Comment by enzo1982** [comment]
Alright, thank you for providing this additional info!

I only had a quick look at the chapter offsets in your first post, yesterday. After taking a closer look now, of course they appear to be correct, just in the wrong order.

As for the `Negative or zero granulepos` error, this appears to be caused by fre:ac indeed. I thought I had changed all sample count fields to 64 bit a long time ago, but must have missed Opus and Speex. They still use a 32 bit sample count field that will overflow for very long outputs (longer than ~12 ½ hours for Opus). I'll fix that in the next update.

Regarding the chapter tag order, I had a quick look at MusicBrainz Picard's source code. It uses Python's dictionary type to store tags. The problem is that before Python 3.6, such dictionaries did not preserve the order of elements added to them.

So if you used a Picard version based on Python 3.5 or earlier, this would explain the chapter tags order getting messed up when editing tags. If you are using a version based on Python 3.6 or later now, this should not happen again. Note that depending on how your version of Picard is packaged, it can use your system-wide version of Python, a Python from a Snap or Flatpak runtime package, or bring it's own version of Python.

**Comment by enzo1982** [comment]
> That said, while doing this I noticed that those converted from very long mp3's seem to get shortened (single mp3 at 32.5 hours went to opus with 7.5 hours) - but will open up a separate issue for that.

That's very likely caused by the 32 bit sample count field too. I'll have a fix for this this evening and there will be new continuous AppImage builds.
