### ISSUE TITLE
Converting 48~96kHz 24bit files to M4A AAC files

### ISSUE THREAD

**Issue by privsecti** [enzo1982/freac#151]
Hi, it's my first time converting 24/48, 24/96 FLAC files to M4A 256kbps files, and I have few questions.
I'm using fre:ac v1.1.2b with Core Audio AAC/ALAC Encoder and AAC Low Complexity 128kbps settings.

1. There seems to be a cutoff above 22kHz after converting 24/48 FLAC files to M4A files. Is this normal? Is there any extra step I should have taken to convert properly?

2. Same question with converting 24/96 FLAC files. Is there anything else I should be aware of when I convert them?

3. When converting same music file in 16/44.1 and 24/44.1 FLAC files to M4A would the resulting files be the same?

**Comment by enzo1982** [comment]
Hi, the Core Audio encoder uses an internal low-pass filter at 22 kHz at 256 kbps, so that's normal. Set the bitrate to 144 kbps per channel / 288 kbps total to avoid that cut-off.

The encoder also internally downsamples higher sample rates to 48 kHz, so there's no point using 96 kHz source material.

Whether you feed 16 bit or 24 bit music to the AAC encoder will not make any real difference in practice. The files will be different due to rounding differences in the least significant bits. Other than that, they will be the same.

Internally, the AAC format has no notion of bits per sample as it works by encoding frequencies instead of samples. Players will usually decode any AAC as 16 bit.

**Comment by privsecti** [comment]
Thank you for detailed answers, it's very helpful.
