### ISSUE TITLE
Automatization options greyed out

### ISSUE THREAD

**Issue by corkyduke** [enzo1982/freac#154]
THANKS ROBERT FOR SUCH A GREAT OPEN SOURCE RIPPER!  I am very impressed and will be donating.

Using v1.1.2. OS is Ubuntu 18.04. Under ripper settings, the automatization options for "Read CD contents on insert" and "Start Ripping Automatically" are greyed out. "Eject Disk after ripping" is available and not greyed out. 

**To Reproduce**
Just did a standard install of 1.1.2 (fresh, no other versions previously installed) and noticed the options are greyed out. There are 3 optical drives in the system. All other functionality appears to work (that is, it is possible to manually get CDDB entries and rip with the 3 drives simultaneously)

**Expected behavior**
All automatization options would be available.

**System **
 - OS: Ubuntu 18.04 Bionic Beaver
 - CPU: Intel Dual Core 
 - RAM: 2GB

**Comment by enzo1982** [comment]
You seem to have installed the Flatpak version of fre:ac. The automatization options are not available there, because they depend on libudev which is incompatible with the Flatpak sandbox.

You can alternatively use the AppImage version which is available here in the [Releases](https://github.com/enzo1982/freac/releases/tag/v1.1.2) area or the [fre:ac Snap](https://snapcraft.io/freac) which should also be listed in Ubuntu Software. Both versions support the automatization features.

**Comment by corkyduke** [comment]
Perfect. Thank you for the information. I will switch to using the Snap version.
