### ISSUE TITLE
Compilation failure on Musl due to IO_ERROR_NOACCESS being undeclared

### ISSUE THREAD

**Issue by PureTryOut** [enzo1982/freac#166]
**Describe the bug**
Freac 1.1.3 fails to compile on Musl systems.

```
 src/jobs/joblist/addfiles.cpp: In member function 'smooth::Int freac::JobAddFilesWorker::Run()':
src/jobs/joblist/addfiles.cpp:216:27: error: 'IO_ERROR_NOACCESS' was not declared in this scope
  216 |  if (in.GetLastError() == IO_ERROR_NOACCESS)
      |                           ^~~~~~~~~~~~~~~~~
```

**To Reproduce**
1. Get a Musl system, for example Alpine Linux in a Docker image will do
2. Install the required deps and try to compile freac

**Expected behavior**
Compilation to succeed

**System (please complete the following information)**
 - OS: Alpine Linux Edge
 - CPU: Irrelevant, compilation problem
 - RAM: Irrelevant, compilation problem

**Additional context**
You can see a build log [here](https://gitlab.alpinelinux.org/PureTryOut/aports/-/jobs/235226#L1584).

**Comment by enzo1982** [comment]
fre:ac 1.1.3 requires smooth 0.9.6 which defines the IO_ERROR_NOACCESS constant. The fre:ac Readme still says smooth 0.9.5, my bad for not updating that.

If you are packaging a new version of smooth, you will want to include commit enzo1982/smooth@0db8f929 on top of the official 0.9.6 release. It will be broken on KDE systems otherwise.

**Comment by PureTryOut** [comment]
Yup Smooth 0.9.6 did the trick, thanks! I applied that patch you mentioned as well.
