### ISSUE TITLE
qaac under Linux not possible

### ISSUE THREAD

**Issue by schfand** [enzo1982/freac#168]
qaac under Linux is not possible
Under Ubuntu 20.04 and Freac 1.1.3

with freac-1.1.3-linux-x86_64.AppImage

**Comment by enzo1982** [comment]
I did some experiments with Ubuntu 20.04 recently and found that the AppleApplicationSupport64.msi is not working there. The encoder will show up in fre:ac, but no formats will be available.

For now, you'll need a 32 bit Wine prefix and install AppleApplicationSupport.msi (the 32 bit version). You can continue using the 64 bit version of fre:ac. It's compatible with both, the 32 and 64 bit encoder.

I'm still investigating what's causing this issue, but it looks like a recent Wine update broke compatibility with the 64 bit encoder. In that case it will have to be fixed in Wine.

**Comment by schfand** [comment]
Only funktion with wine32 bit default ./wine not with another Wine32 bit installation. For example ./wine32

**Comment by enzo1982** [comment]
Finally had some time to take a closer look at this and I found a solution.

I used to use a separate Wine prefix for 32 and 64 bit, but that doesn't seem to be necessary anymore. Regular 64 bit Wine can now deal with 32 bit binaries too. It's not necessary to have a separate 32 bit prefix.

So, instead of installing AppleApplicationSupport64.msi, you can simply install AppleApplicationSupport.msi to avoid the Wine incompatibility issue. In case the 64 bit version is already installed, it can be removed using `msiexec -uninstall AppleApplicationSupport64.msi`.

This would be all in the best case, but unfortunately, I found another issue with fre:ac. Version 1.1.3 was supposed to add compatibility with newer iTunes versions that come without separate Apple Application Support packages. I accidentally introduced a bug in the new code, though, so that only the newer iTunes versions are recognized now (iTunes 12.10.9 and later).

This bug is already fixed in the latest [continuous builds](https://github.com/enzo1982/freac/releases/tag/continuous). So the above solution to use the 32 bit Apple package only works with fre:ac 1.1.2 or the latest continuous build, not with fre:ac 1.1.3.

**Comment by enzo1982** [comment]
fre:ac 1.1.4 is available now with fixes for the issues discussed here.

I was able to get fre:ac working with the Core Audio encoder on a freshly installed Ubuntu 20.04 by following these steps:

- install Wine using sudo apt install wine
- download the Apple iCloud Client (iCloudSetup.exe) from Apple and install it using Wine
- download and run the fre:ac 1.1.4 AppImage

When manually extracting and installing the Apple Application Support packages, it's important to install the 32 bit version AppleApplicationSupport.msi.

Closing this.
