### ISSUE TITLE
Crash after first few encodings in Windows 10; reinstall does not fix

### ISSUE THREAD

**Issue by laelume** [enzo1982/freac#176]
After a few encodings (maybe 3-5 like previous reports said?) of .aiff to .mp3 whereby the first few .mp3 files play back correctly and sound GREAT, each subsequent attempt at encoding results in a crash of the software, and the "crashed encoding" produces a file with a .mp3 tag, but the file is not actually playable. Playback engine errors from VLC:
```
File reading failed:
VLC can't recognize the input's format:
The format of 'file:///C:/Users/drSeuss/bleep.mp3' cannot be detected. Have a look at the log for details.
```
OS: Windows 10 v:1909 Build:18363.1198
CPU: Intel i7 10750H
RAM: 16GB

freac-1.1.3-windows-x64

This has happened every time after the first few encodings, even after uninstalling and reinstalling :(

Edit: Just uninstalled again and now trying freac-1.1.1-windows-x64. This converts the files without the "blank file" problem as mentioned above, but now only a small portion of the audio is being converted, not lasting more than ~30s. Have tried multiple audio files all with same result. 

Also, the GUI shuts down after the encoding is finished, even though "shutdownAfterEncoding" is set to False...

**Comment by enzo1982** [comment]
Thank you for reporting this!

This sounds like it might be an unexpected format of the source files causing fre:ac to crash. Do these issues happen only when trying to convert your .aiff files or also when converting other files like .wav or .mp3?

If it only happens with the .aiff files, it would be great if you could sent me one of them for analysis. There's a good chance that I will be able to reproduce the issue here if I have the file. You can send a link (or the whole file if it's not too large) to support@freac.org.

Also, could you try with fre:ac 1.1.2 to narrow down the version that introduced the behavior change? Your description sounds as if both 1.1.1 and 1.1.3 are crashing, but in a slightly different way, so knowing what change introduced that might be helpful.

**Comment by Permofit** [comment]
I am having the same issue but i am converting .m4b and mp3 to m4a it will convert a dozen or so then just shut down and close I am also on win 10

**Comment by enzo1982** [comment]
@laelume and @Permofit Could you check again with fre:ac 1.1.5? The new update comes with several fixes for crashes including some related to MP3 decoding and encoding, so I hope that these issues might be fixed.

**Comment by enzo1982** [comment]
Closing this as there was no response after my last comment. Please reopen if the issue persists after upgrading to 1.1.5.
