### ISSUE TITLE
Does not automatically start ripping

### ISSUE THREAD

**Issue by TippyLion28** [enzo1982/freac#181]
**Describe the bug**
I've enabled "start ripping automatically" but it doesn't automatically start after inserting an audio CD

**To Reproduce**
1. Enable auto ripping
2. Insert a cd
3. Freac gets metadata and populates the joblist, but then does nothing 

**Expected behavior**
Should start automatically ripping 

**Screenshots**

**System (please complete the following information)**
 - OS: Windows 10 (also tried Ubuntu) 
 - CPU: Intel Core i7 4700
 - RAM: [16GB]

**Additional context**

**Comment by enzo1982** [comment]
I cannot reproduce this here, but I have some notes.

Automatic ripping is active only when the disc was also added to the joblist automatically. When you click the "Add CD tracks" button, ripping will not start automatically. That's intentional.

Unfortunately, automatic adding to the joblist is a bit flakey on Windows. Sometimes, Windows simply does not send a notification about a newly inserted CD, so automatic adding of the disc will not be triggered.

Also, automatic ripping will start only if CDDB queries are enabled and the CDDB query is successful. The reasoning behind this is that when there is no data for a disc, the tracks will all be called "unknown title" and tracks from subsequent discs would overwrite earlier ones. Automatic ripping is not started in that case to give you a chance to enter the actual track names.

Unfortunately, this is tied to CDDB queries in the current version of fre:ac. This will be changed in the next version to check for the actual presence of track titles instead (which may also have been read from CD-Text).

**Comment by TippyLion28** [comment]
Ah this makes sense. I couldn't get CDDB queries to work properly so it wasn't automatically ripping the tracks. Although, I did have the "append number to otherwise identical filenames" enabled, which would avoid the issue you mentioned. Maybe this could be added as a mitigating factor?

**Comment by enzo1982** [comment]
I thought about that, but it would be only marginally better than overwriting existing rips. If you rip multiple CDs without metadata that way, the files would all land in the same folder and the appended numbers would not stay in sync for each CD, as each one would have a different number of tracks.

So I'd like to keep it as it is. The situation will still become a bit better with the next release, though. CD-Text support will be improved to enable reading it in some case where it didn't work correctly before. And as mentioned above, the availability of CD-Text will be enough to allow automatic ripping - no CDDB required in that case.

Regarding CDDB, though, the GnuDb project had some issues due to a failed router last week. So maybe just try it again and it might work now.

**Comment by TippyLion28** [comment]
Ah okay, cheers! Will close this issue now :)
