### ISSUE TITLE
Not ripping at full speed

### ISSUE THREAD

**Issue by TippyLion28** [enzo1982/freac#182]
**Describe the bug**
When ripping audio CDs, it only seems to take full advantage of 48x ten percent of the time. It seems to be sticking my drive at only 16x. I'm fully aware this could be an issue with my specific setup, so please say if this is likely the case :) 

**To Reproduce**
1. Start ripping
2. Doesn't rip at full speed 

**Expected behavior**
Should rip at full speed

**Screenshots**

**System (please complete the following information)**
 - OS: Windows 10 and also tried Ubuntu
 - CPU:  Intel Core i7 4700
 - RAM: 16 GB

**Additional context**

**Comment by enzo1982** [comment]
This does not seem too unusual. In fact, most drives advertise much higher speeds than they can actually reach.

First, you have to consider that CD drives run at constant angular velocity. So during one rotation, more sectors pass the laser when reading from the edge of the disc as compared to the center. A drive advertised as 48x will reach full speed only when reading the last few seconds of the final track of an 80 min CD. You'll never reach an average speed of 48x and you'll never reach 48x reading the first track or a track from the middle of an album.

For example, I just tested ripping with a 72 min disc in a 48x drive. The drive starts at 18.2x speed for the first track. It goes up to 38.9x for the last track. The average speed reading that CD was 28.8x. However, the last track is almost 10 minutes long, so I assume that at the end of that track the drive reaches more than 41x speed. If the CD was 80 min or even more (there were CDs with up to 90 min), I could see the drive reaching its advertised 48x speed.

It can also depend on the CD what speed a drive can reach. If a drive has difficulties getting a clear read at high speeds, it may slow down automatically. This can be caused by scratches on a CD, different reflective materials used in production or - especially in the case of CD-Rs - the age of the CD.

And finally, it can depend on the combination of drive and CD. For example, I have a disc that happily rips at full speed in most of my drives, but one drive will just never accelerate to full speed with that one disc. It rips it at 16x speed maximum. Although it will go up to about 40x with other CDs.

**Comment by TippyLion28** [comment]
Wow, thanks very much for the detailed explanation. I was wondering why I'd see the read speed increasing but didn't hear the motor spinning any faster - this explains that well. It looks like my drive is struggling to get good reads with these CDs at high speeds. Many of them have not been kept in great condition (scratches, grease, dirt etc). Meanwhile some of the newer, cleaner looking CDs have been able to more often hit that top speed. Will close this issue now, thank you :)
