### ISSUE TITLE
Core Audio AAC/ALAC Encoder?

### ISSUE THREAD

**Issue by NeverSm1le** [enzo1982/freac#183]
Really sorry I have to use this "bug report" tag, I just wanted to ask a question. Folks from hydrogen audio mentioned that there is a Core Audio AAC/ALAC Encoder in freac but I can't seem to find it, just Apple Lossless Encoder. I'm currently on 1.1.3. Is this encoder only exist in the old version?

Edit: finally understand. Closing now

**Comment by enzo1982** [comment]
Just a quick answer in case someone having the same question finds this later:

The Core Audio encoder is not part of fre:ac, but included with Apple's iTunes and the iCloud client. On Windows it's sufficient to install either iTunes or the iCloud client and the encoder should show up in fre:ac.

On Linux or FreeBSD you'll need to install iTunes or the iCloud client in Wine to use the encoder in fre:ac. Alternatively, extract the AppleApplicationSupport.msi package from iCloudSetup.exe and install only that using msiexec. Due to sandboxing, this will not work with the Snap and Flatpak packages of fre:ac, only with the AppImage version. There also are some issues with fre:ac 1.1.3 and recent versions of Wine. Make sure to use the continuous build version of fre:ac and the 32 bit AppleApplicationSupport.msi, not AppleApplicationSupport64.msi (you can use the 64 bit version of fre:ac though).
