### ISSUE TITLE
Short OGG files are decoded as 'blank'

### ISSUE THREAD

**Issue by czaccardelli** [enzo1982/freac#190]
**Describe the bug**
When OGG files (only type I tested) that were short ( < 0:01 seconds) were loaded, fre:ac previewed them as 'blank' and also output them as 'blank' (aka no sound).

**To Reproduce**
1. Load short OGG file (some attached).
[samples.zip](https://github.com/enzo1982/freac/files/5953751/samples.zip)

2. Try to play or convert it.
3. Notice it has no sound.

**Expected behavior**
Hear sound.

**System (please complete the following information)**
 - OS: Windows 10 build 19041
 - CPU: Intel Core i5-6600K
 - RAM: 16GB

**Comment by enzo1982** [comment]
This has already been reported by another user and is fixed in the sources already. The fix will be in fre:ac 1.1.4 which will be available in a few days.

If you don't want to wait, you can download a fixed version of fre:ac's Vorbis decoder component from https://freac.org/updates/freac-1.1.3-vorbis-fix.zip.

To use it, extract the included `boca_decoder_vorbis.1.0.dll` file and copy it to the `boca` subfolder in your fre:ac 1.1.3 program directory, replacing the existing file.

**Comment by enzo1982** [comment]
fre:ac 1.1.4 is now available with the fix for this issue.
