### ISSUE TITLE
The option to see channels in the joblist.

### ISSUE THREAD

**Issue by L0garithmic** [enzo1982/freac#206]
Would like the option to see channels in the joblist. This is especially helpful when converting using encoders that have a per-channel option like FDK, it's a pain to have to go check every single file before encoding to check their channels. 

Unless, you can add an option to the FDK encoder to do overall-bitrate rather then per-channel...

**Comment by enzo1982** [comment]
You can enable the _Channels_ column on the _Joblist_ page of the configuration dialog.

However, please note that using the same overall bitrate for files with different channel configurations will result in varying audio quality. E.g. a mono file at 96 kbps will sound transparent, while a stereo file at the same bitrate will sound slightly worse and a 5.1 file will sound very bad. That's why the bitrate setting was changed to per-channel, to provide more uniform output quality.

**Comment by L0garithmic** [comment]
I swear. Every time I ask for a feature. You already have it... I just can never find it!!! lol
Thanks!
