### ISSUE TITLE
Windows 10 - Access to CD-ROM drives was denied by Windows.

### ISSUE THREAD

**Issue by fichtennadel** [enzo1982/freac#211]
**Describe the bug**
Error message "Access to CD-ROM drives was denied by Windows." when starting fre:ac

**To Reproduce**
1. start freac.exe
2. ![image](https://user-images.githubusercontent.com/2324670/117828591-3cbd8000-b272-11eb-80cc-63c43ef5ee28.png)
3. no access to CD-ROM 

**Expected behavior**
1. start freac.exe
3. access to CD-ROM 

**System**
 - OS: Windows 10 Build 20H2 64bit Pro
 - CPU: i5-10400
 - RAM: 16 GB

**Additional context**
I've already checked https://github.com/enzo1982/freac/issues/99 and tried with disabled Windows Defender real-time protection, but this didn't help.

BUT: starting freac.exe with admin rights circumvents the issue. I've made a trace with sysinternals' procmon, the traces start to differ on these lines:

*freac.exe with user rights, failing*
![image](https://user-images.githubusercontent.com/2324670/117829376-ffa5bd80-b272-11eb-99d0-bea008a2267b.png)

*freac.exe with admin rights, ok*
![image](https://user-images.githubusercontent.com/2324670/117829567-2e239880-b273-11eb-8952-25403e26056c.png)

**Comment by enzo1982** [comment]
On Windows 10, this is usually caused by the _Controlled folder access_ feature which denies access to CD drives.

To disable it, follow these steps:

- Open the _Windows Security_ center
- Select _Virus & threat protection_
- At the bottom of that page, select _Manage ransomware protection_
- Disable _Controlled folder access_

Alternatively, add fre:ac to the list apps exempt from controlled folder access or use the fre:ac version from the Microsoft store. Microsoft store apps are automatically exempt from controlled folder access.

I'm not 100% sure that this feature is responsible for the issue in this case, though. Controlled folder access usually denies access to drives when running with admin rights too, so it might be something else here.

**Comment by enzo1982** [comment]
Oh, alright. Thanks for your quick reply!

In that case it must actually be the local security policy interfering with CD drive access. Windows restricts drive access to locally logged on users by default. You can control that policy in the local security policy settings.

To access the setting:

- Search for local security policy in the start menu and open it
- Open the _Local Policies_ and then the _Security Options_ sub-folder
- There should be an option _Restrict CD-ROM access to locally logged-on users_

That feature caused lots of trouble in the Windows XP days, when Windows XP Pro interpreted this setting somewhat weirdly and restricted access even for locally logged on users.

On Windows XP you counter-intuitively had to set that to _Enabled_ to allow locally logged on users to access the CD drive. I'm not sure how this needs to be configured on Windows 10 to allow remote users to access the drive, but you can give it a try.

**Comment by pidg** [comment]
I'm also experiencing this, as I log into my Windows 11 media server (where fre:ac lives) remotely.

The precise policy is called "Devices: Restrict CD-ROM access to locally logged-on user only", but it doesn't seem to make a difference to this issue (whether you set it to Enabled or Disabled).

Weirdly this was never a problem when I was on Windows 10, so I'm not sure what changed.
