### ISSUE TITLE
Winget porting

### ISSUE THREAD

**Issue by tiziodcaio** [enzo1982/freac#216]
# Winget porting

## Describe the solution you'd like

As described [here](https://github.com/microsoft/winget-pkgs#submitting-a-package), you can submit a package not to hardly...

**Comment by enzo1982** [comment]
I'm not sure I want to invest time in this. fre:ac is available in the Microsoft store and Microsoft is adding support for installing store apps to Winget (see microsoft/winget-cli#117), so this will eventually be resolved by them.

Otherwise, adding fre:ac to Winget would require some effort as the current installer does not have a silent mode. The alternative would be to build .msix packages and release them in addition to the current installer and .zip packages. I'd rather save the time to do that and put it into improving the core application.

**Comment by tiziodcaio** [comment]
ok we will wait! In the case this will change I will happy to add it.
For now should I close the issue?

**Comment by enzo1982** [comment]
Let's leave the issue open as a reminder.

**Comment by tiziodcaio** [comment]
Sure

**Comment by enzo1982** [comment]
Winget now officially supports the Microsoft store, so fre:ac can be installed with `winget install -s msstore fre:ac`.

Closing this issue.

**Comment by microbearlogist** [comment]
The package name is not anymore recognized.
The following identifier should be used instead: 9P9TQF7MRM4R


`winget install -s msstore 9P9TQF7MRM4R`

The identifier is indicated in the application address on https://apps.microsoft.com

**Comment by maphew** [comment]
The ID has changed.
```
» winget search "free audio"
Name                               Id             Version Source
------------------------------------------------------------------
Free Audio Joiner                  9NVW23XVRLGV   Unknown msstore
DVDVideoMedia Free Audio Converter XP89FK75TZFWWS Unknown msstore
Free Audio Remover                 XPDDS70XZBCVK3 Unknown msstore
fre:ac - free audio converter      9P1XD8ZQJ7JD   Unknown msstore
```
It's not necessary to specify store as source. The below works.

` winget install 9P1XD8ZQJ7JD`

**Comment by Ivoz** [comment]
It would be cool if you could make msix, because otherwise `chocolatey` tool cannot use any silent method to install fre:ac. Thanks for your tool. The current version is only copying a 'portable' version, but that can't make things like start menu shortcuts etc
