### ISSUE TITLE
Vorbis encoder crash

### ISSUE THREAD

**Issue by axredneck** [enzo1982/freac#219]
**Describe the bug**
Crash when i try to encode something to Vorbis

**To Reproduce**
1. Run continuous build appimage (commit b92b148)
2. Add something to encode
3. Set encoder to Ogg Vorbis
4. Start encoding
5. Crash

**System (please complete the following information)**
 - OS: Arch Linux
 - CPU: Ryzen 5 2600
 - RAM: 16 GB

**Additional context**
```
redneck@pylesos ~/programs> ./freac-continuous-linux-x86_64.AppImage
fish: Job 1, './freac-continuous-linux-x86_64…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by enzo1982** [comment]
Thank you for reporting this!

I was able to reproduce the issue on Manjaro. It also affects fre:ac 1.1.4.

This was due to fre:ac loading the libvorbis.so shipped with the AppImage, but the libvorbisenc.so from the host system. Somehow the libvorbisenc.so from the AppImage refused to load when a libvorbis.so was present in /usr/lib. This is fixed in the latest continuous build.

**Comment by axredneck** [comment]
Thank You!
