### ISSUE TITLE
regression: drag+drop doesn't work any more under Windows, since v1.1.5

### ISSUE THREAD

**Issue by IDC-Dragon** [enzo1982/freac#226]
**Describe the bug**
After updating to v1.1.5, I coudn't use drag+drop any more. A downgrade to v1.1.4 made it working again.

**To Reproduce**
1. Install v1.1.5
2. Try to drag a folder / music file to the main screen
3. See a minus symbol for mouse cursor, indicating reject, no files accepted

**Expected behavior**
3. See a plus symbol, indicating drop acceptance, add files

**System**
 - OS: Windows 10 Pro 64 bit, version 1909, build 18363
 - CPU: Intel Core i7 3770K
 - RAM: 24 GB

**Additional context**
Installing v1.1.4 instead fixed it for me.

**Comment by enzo1982** [comment]
Drag & drop is working fine with v1.1.5.

The problem you describe occurs on Windows, when trying to perform drag & drop between applications running at different privilege levels. Windows allows drag & drop between programs running at the same privilege level only.

This situation can occur after upgrading fre:ac with the integrated updater. The updater requests elevated privileges in order to be able to perform the update. Then, after it is done, it starts the new version of fre:ac. However, as the updater is running at elevated privileges, so will the newly started instance of fre:ac. Unfortunately, Windows does not provide an easy way to run a program at non-elevated privileges from a program running elevated (there is a complex way, though, which I plan to eventually implement in a future version of the updater).

**Comment by IDC-Dragon** [comment]
Ah, just re-tested, sorry, thank you for the explaination.
To avoid further confusion, maybe the program should just exit after the update, telling the user to restart it? I think this is smaller hassle than having it running in a state where it doesn't work as expected. Plus, it is more safe. In elevated mode, network drives may not be accessible (depending how their share got mounted).

**Comment by enzo1982** [comment]
I gave this another try and found a solution that maintains backward compatibility with older versions of Windows (fear that this might break compatibility was the main reason why I originally considered waiting for fre:ac 1.2 to implement a solution).

The fix will be shipped with the next update (1.1.6), but will effectively solve the issue only for the update following that (probably 1.1.7). From then on, the restarted fre:ac will run non-elevated which will fix drag & drop and other possible issues.
