### ISSUE TITLE
Changing "Active Configuration" (config profile) from main interface?

### ISSUE THREAD

**Issue by thw0rted** [enzo1982/freac#240]
**Is your feature request related to a problem? Please describe.**
I use `fre:ac` for two primary purposes: ripping CDs to MP3s, and converting audiobooks that I already have as individual (MP3) tracks into single M4A / M4B books with chapter markers.  So, depending on context, I either want to encode to MP3 (LAME) multi-file or AAC single-file.  I created separate profiles in the General Settings dialog, but have to re-open General Settings each time I switch between these types of tasks.

**Describe the solution you'd like**
I'd like a small drowndown selection, button, or menu entry that lists all profiles (configurations?) and lets me pick one with a click.

**Describe alternatives you've considered**
Open settings menu, click Active Configuration, change configuration, "OK".  (Keyboard focus doesn't seem to work, so I can't tab around.)

**Additional context**
Being able to do all of this purely with the keyboard would be nice.

**Comment by thw0rted** [comment]
Just remembered I meant to ask about the keyboard thing I mentioned in the issue.  Standard conventions like alt+letter to open a menu or tab focus don't seem to be supported.  Would it make sense to request keyboard navigation support here, or in https://github.com/enzo1982/smooth/ ?

**Comment by enzo1982** [comment]
When there are multiple configurations, a drop down list appears next to the configuration toolbar button (first button in the third group), allowing you to quickly change the active configuration.

The same list is also available in the menu under _Options->Active configuration_, but the toolbar button drop down should be easier to reach.

As for keyboard support, that's been on my wishlist for a very long time already, but I never had the time to actually implement it. Also, it's not requested very often, so other features had a higher priority for me in the past.

Feel free to open a separate issue for that though. And please open it here. Most of it will have to be implemented in smooth, but some changes like defining the menu accelerator keys will have to be done in fre:ac. So it makes sense to have the issue here.

**Comment by thw0rted** [comment]
Well, I *swear* I did look for that before posting, but now that you point it out it seems embarrassingly obvious. 😳

Sorry, and thanks for taking the time to reply!  (I filed #243 for keyboard navigation.)
