### ISSUE TITLE
How are armhf AppImages built?

### ISSUE THREAD

**Issue by lucasmz1** [enzo1982/freac#250]
how do you join all the libs for the version armhf, how did you deploy it ? I wanna make appimage in arhf but I dunno how to do it without linuxdeploy? do you have any linux deploy for armhf?

**Comment by enzo1982** [comment]
Hi, I don't use linuxdeployqt, but [AppImageKit](https://github.com/AppImage/AppImageKit) to build the AppImage. AppImageKit is available for armhf.

You can see how the fre:ac AppImages are built by looking at the GitHub Actions workflow and the scripts it uses. The main workflow file is [continuous-build-linux.yml](https://github.com/enzo1982/freac/blob/master/.github/workflows/continuous-build-linux.yml). This installs some dependencies (e.g. the armhf toolchain and qemu in order to run armhf binaries) and then calls the [build-appimage](https://github.com/enzo1982/freac/blob/master/.github/workflows/tools/build-appimage) script which builds fre:ac and then packages it using AppImageKit.

**Comment by lucasmz1** [comment]
got it, thank you.
