### ISSUE TITLE
Snapshots README has changelog of stable version

### ISSUE THREAD

**Issue by kq01526** [enzo1982/freac#26]
Hi @enzo1982 ,

the snapshots README shows the changelog of the stable version, so it's not possible to tell what has been changed in the snapshots (other than having a look at https://github.com/enzo1982/freac/releases which also only does not include all previous releases).

Is there a comprehensive changelog available anywhere?

Regards

**Comment by enzo1982** [comment]
The fre:ac 1.1 alpha Readme file lists the changes as compared to the latest stable release (1.0.32 as of now).

Alpha changes as compared to the previous alpha are listed in the GitHub releases for the past year or so.

If you would like to know the most important changes of each snapshot or alpha release since the beginning, they are mentioned in the news items on https://www.freac.org/latest-news-mainmenu-2.

More detail is found only in the individual commit messages of the [smooth](https://github.com/enzo1982/smooth/commits/master), [BoCA](https://github.com/enzo1982/boca/commits/master) and [fre:ac](https://github.com/enzo1982/freac/commits/master) repositories.
