### ISSUE TITLE
M4A files issue

### ISSUE THREAD

**Issue by noblogo** [enzo1982/freac#261]
**Describe the bug**
M4A files are not opening in the last version.

**Screenshots**
fre:ac screens "error during the treatement / impossible to open x.m4a file"

**System (please complete the following information)**
 - OS: windows 10

**Comment by enzo1982** [comment]
Loading ,m4a files (AAC and ALAC) works fine for me here.

And can you make the .m4a file you are trying to load available to me for analysis? I'll then be able to see what is going wrong.

If you cannot attach the file here, please upload to a cloud drive and share a link to support@freac.org.

**Comment by RodneyRabbit** [comment]
I'm getting the same issue with the latest 1.1.6 update on Windows 10 x64 21H2 19042.804. I was converting files this morning on 1.1.5 then installed the update just now and it no longer opens M4A files, either newly downloaded ones or older ones from my library that I downloaded months ago. MP3 files open fine though.

It did the update from the update checker first but I tried running the 1.1.6 installer package and also tried installing 1.1.5 again over the top and now that won't open them either, so not sure what's happened.

[https://i.imgur.com/O3aJSQB.png](https://i.imgur.com/O3aJSQB.png)

**Comment by RodneyRabbit** [comment]
Actually I really needed to convert some files so I installed 1.1.5 in a clean VM and it opened the files no problem. When I was done I kept reverting the VM and I tried three ways to install 1.1.6:

- Update from 1.1.5 using the update checker.
- Installing 1.1.6 over the top of 1.1.5.
- A clean install of 1.1.6 with no prior version.

I was testing with the exact same M4A file each time and in all cases 1.1.6 wouldn't open the files.
Additionally, after 1.1.6 had been installed I tried reinstalling 1.1.5 in the VM and it too would no longer open M4A files just like my main PC in my last comment.

This VM is an older OS (Win 10 x64 20H2 19042.804) so I don't think a recent Windows update has caused it.

1.1.5:
[https://i.imgur.com/P0h5EFT.png](https://i.imgur.com/P0h5EFT.png)

1.1.6:
[https://i.imgur.com/rou4KoN.png](https://i.imgur.com/rou4KoN.png)

**Comment by enzo1982** [comment]
@noblogo sent me a file and it turned out to be a DASH file. Those are not officially supported by fre:ac yet - never have been. However, when switching the ALAC decoder from a separate external decoder over to FFmpeg some time ago, that introduced the ability to decode DASH files as a side-effect (as FFmpeg supports such files).

With fre:ac 1.1.6 switching the ALAC decoder to an internal one, it does not try FFmpeg on DASH files anymore, which removed the ability to decode such files.

DASH is a special internal layout for MP4 files that is optimized for streaming (hence it is used by YouTube et al.) and differs from the usual MP4 layout used for regular M4A/AAC files.

I've had plans to add DASH support for a while already, so maybe it's time to do that now. I've set up a fork of the MP4v2 library used by fre:ac to handle MP4 files. Still working on fixing the build system, but after that I'll look into adding DASH support (and some other features like support for writing ALAC files).

In the meantime, here is a generic M4A decoder script: [boca_decoder_ffmpeg_m4a.1.0.zip](https://github.com/enzo1982/freac/files/7964096/boca_decoder_ffmpeg_m4a.1.0.zip)

Add the .xml file from the ZIP to the boca folder inside fre:ac's program directory and it should be able to handle DASH files again.

**Comment by noblogo** [comment]
Thanks a lot for the mystery explained, Enzo !
