### ISSUE TITLE
Rewrite if no metadata possibly ?

### ISSUE THREAD

**Issue by r3l1c** [enzo1982/freac#282]
Trying to convert multiple files ( different filename ) - but fre:ac finds no metada so i assume it wants to all make em "unknown" ... so it asks if i want to overwrite all files as they already exist - even though they dont. ( if you press yes - then ) 

So it converts one file.. then the next overwrites the first one and so on... 
so instead of 33 files .. you end up with one.

Windows 10@64 1.1.6 ( latest version at the day of posting this - 64bit version )

**Comment by enzo1982** [comment]
That's normal when there is no metadata present in the source files. You can change the _output filename pattern_ to `<filename>` in the config dialog to preserve the original file names instead of generating new ones.

I'll add an option to automatically fall back to using the source file name when there is no metadata available in a future fre:ac release.

**Comment by r3l1c** [comment]
> That's normal when there is no metadata present in the source files. You can change the _output filename pattern_ to `<filename>` in the config dialog to preserve the original file names instead of generating new ones.
> 
> I'll add an option to automatically fall back to using the source file name when there is no metadata available in a future fre:ac release.

That worked out :) took me a minute to find
