### ISSUE TITLE
Make Fre:ac relocateable

### ISSUE THREAD

**Issue by probonopd** [enzo1982/freac#29]
Fre:ac on Linux seems to try to load stuff from a `../lib/freac` directory, _relative to the system-wide library directories_.

This fails when Fre:ac is not installed into a system-wide prefix (like `/usr`), but to a relocateable bundle that can be stored anywhere in the filesystem:

```
stat("/usr/local/lib/../lib/freac/freac.so", 0x7fffed1d5d50) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/../lib/freac/freac.so", 0x7fffed1d5d40) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/../lib/freac/freac.so", 0x7fffed1d5d50) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/x86_64-linux-gnu/../lib/freac/freac.so", 0x7fffed1d5d40) = -1 ENOENT (No such file or directory)
stat("/lib/x86_64-linux-gnu/../lib/freac/freac.so", 0x7fffed1d5d40) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/../lib/freac/freac.so", 0x7fffed1d5d40) = -1 ENOENT (No such file or directory)
```

Hence, the `../lib/freac` directory should be computed as a path relative to the main executable (e.g., using `/proc/self/exe`) on Linux.

References:
* https://github.com/probonopd/freac/blob/patch-1/.travis.yml
* https://github.com/probonopd/freac/releases

**Comment by enzo1982** [comment]
fre:ac already tries loading `freac.so` relative to its main executable before resorting to trying system-wide library directories. That is, before trying to load `/usr/local/lib/../lib/freac/freac.so` it will have tried `<path-to-freac>/freac.so` and `<path-to-freac>/../lib/freac/freac.so` already which must have failed for some reason. My guess would be that some dependencies of `freac.so` are missing in your runtime environment. Maybe you need to include additional libraries in your bundle. Can you check with ldd?

I built a fre:ac Flatpak in December and am building a Snap right now where the runtime environments are similar, but I didn't run into issues loading `freac.so`.

**Comment by probonopd** [comment]
Thaks for your response @enzo1982. Could you please have a look at:

```
wget -c "https://github.com/probonopd/freac/releases/download/continuous/fre.ac-e0ee031-x86_64.AppImage"
chmod +x fre.ac-e0ee031-x86_64.AppImage 
./fre.ac-e0ee031-x86_64.AppImage --appimage-extract
./squashfs-root/AppRun # FAILS
```

**Comment by enzo1982** [comment]
The freac.so in your bundle cannot resolve its dependency on `libboca-1.0.so.0` even though that library is present in `usr/lib` in the bundle.

Running `LD_LIBRARY_PATH=squashfs-root/usr/lib ./squashfs-root/AppRun` works as does copying `libboca-1.0.so.0` to a system-wide library path and then running `./squashfs-root/AppRun`.

The root cause is that the `usr/lib` folder is referenced only in the rpath of `usr/bin/freac` (which is set to `$ORIGIN/../lib`). The dynamic loader, however, does not consider that path when loading `freac.so`. To fix this, `freac.so` should have its rpath set to `$ORIGIN/..` when linking I guess.

Try changing line 111 in the Makefile to something like:

`
	LDOPTS_DLL		+= -Wl,-rpath,$$ORIGIN/.. -lboca-$(BOCAVER)
`

**Comment by probonopd** [comment]
Thanks for your analysis @enzo1982. I will see what I can do.

**Comment by probonopd** [comment]
> To fix this, freac.so should have its rpath set to $ORIGIN/.. when linking I guess.

Thanks, this did the trick.
