### ISSUE TITLE
How to encode the audio bit rate as low as 8kbps 16kbps

### ISSUE THREAD

**Issue by duytrung** [enzo1982/freac#291]
Good day @enzo1982 ,

I'm not quite sure this is a feature request or a bug but I have tried to encode an mp3 with low bit-rate as 8kbps, 16kbps with variable bit rate but found the final file has a bit rate of 32kbps with lame encoder in mono mode. Did I missed something?

Thank you very much

**Comment by enzo1982** [comment]
The MP3 format supports 8 and 16 kbps bitrates only at sample rates up to 24 kHz. Normally, LAME will automatically downsample to that rate if the input sample rate is higher. However, checking the _Disable all filtering_ option the _Audio processing_ tab prevents it from downsampling, so the minimum supported bitrate is then 32 kbps.

So I assume you disabled LAME's internal filtering and that's why you get 32 kbps files.

To get down to 8 or 16 kbps, either enable LAME's filtering or use fre:ac's sample rate converter to downsample to 24 kHz.

**Comment by duytrung** [comment]
Thank you very much @enzo1982 
That makes sense to me I will take a note :-)
