### ISSUE TITLE
fre:ac crashes when transcoding large number of files

### ISSUE THREAD

**Issue by StephenMNolan** [enzo1982/freac#292]
I ripped my entire CD collection using fre;ac to ALAC for archive purpose. Now I'm trying to batch transcode from ALAC to AAC for upload to iPhone. When I load a whole genre (e.g. Classical about 200 tracks) and start transcoding, fre:ac crashes (shuts down) after just 20 or 30 files. Windows 11.

**Comment by enzo1982** [comment]
Thank you for reporting this! I cannot reproduce the issue here, but I'm seeing a number of crashes in the ALAC decoder module reported for the fre:ac Windows Store app.

I suspect that certain ALAC files are causing the crash, i.e. it should be unrelated to the number of files you try to convert in one go, but the crash would always happen at the same file.

If you can reproduce the issue reliably with your 200 files set, can you try to reduce the number of files and attempt to find out which file causes the crash? I will then need that file for further analysis.

**Comment by enzo1982** [comment]
OK, _not consistently repeatable_ makes it sound more likely to be related to parallel conversion of multiple files indeed. It's possible that the reports I'm seeing for the Windows Store app are a different issue.

Anyway, I'll keep an eye on this and continue to experiment with this myself.

One more question though: Did you create the ALAC files with fre:ac or with a different program?

**Comment by StephenMNolan** [comment]
100% of the ALAC files were ripped from music CDs using fre:ac. 

Some of them were done using fre:ac on my old MacBook Air running Catalina but for some reason it quit recognizing the USB CDROM drive.

So then I switched to my new Dell XPS-13 laptop running Windows 11 and that was what was used for the majority of the ripping of the music CDs to ALAC.

**Comment by enzo1982** [comment]
Alright, thanks!

**Comment by StephenMNolan** [comment]
A couple of other things: 

I just checked my Windows Store and it appears I installed fre:ac using the Windows Store since it is in the software list there.

Also, I was using fre:ac on my Dell XPS-13 laptop running Windows 11 to do the transcoding from ALAC to AAC. I haven't tried it on the old MacBook Air as it is much slower (very old computer).

**Comment by StephenMNolan** [comment]
Thank you! Great software.

**Comment by enzo1982** [comment]
So... I took another look at the Windows Store crash reports and finally, for one of the ~80 reports there was a stack trace and minidump available for me to inspect.

It looks like what is happening is the ALAC decoder reading past the supplied buffer as an optimization (it always reads 32 bits ahead even if the value to read is shorter). The problem with this is when the buffer ends at a memory page boundary and the next page does not belong to fre:ac, this will crash on systems with strong memory protection.

This is a bug in Apple's ALAC decoder code, but fortunately can be worked around by making the buffer a bit larger. After doing this, I can no longer reproduce the crash even when converting a large number of ALAC files.

This also explains why the crash was not reproducible all the time. In separate runs of fre:ac, buffers will be allocated at different memory addresses. So the end of a buffer will not always be at a page boundary.

The exact same thing happened with the FDK-AAC decoder before. There the crash occurred about once in 2000 attempts at decoding AAC files. I had fre:ac running and decoding AAC files for hours back then in order to reproduce the crash...

This here was much easier to reproduce, but only with the Microsoft Store version of fre:ac (I assume the runtime for store apps has stricter memory protection).

This will be fixed in the next release, but as this happens mainly with the Microsoft Store version, I will release an update for that prior to the next general release.

**Comment by StephenMNolan** [comment]
Wow! That's pretty amazing forensic work on your part! 

I'll check Microsoft Store for a program update. 

Thanks, again!!

**Comment by enzo1982** [comment]
The update is now available in the store. Microsoft always takes a few days to verify new releases. The update is listed as version 1.1.6001.0 in the store. You won't see a difference in the fre:ac UI as only the ALAC decoder component has be replaced.

Would be great if you could give this a try to verify the fix.

**Comment by StephenMNolan** [comment]
Robert, the new update does show up in Microsoft Store. I did an "Update All" and it looks like it updated. 

I won't have time to try any batch conversions for a few days, but I'll try to keep it in my "to do" list and let you know. 

As noted above, I previously got it to convert >2600 files by not doing anything else at the same time. So to "stress test" it I'll try watching YouTube videos in Google Chrome while doing the batch conversions. That seems to have help cause it to fail before (just a theory). Will let you know.

**Comment by enzo1982** [comment]
Great! Thanks for reporting back!
