### ISSUE TITLE
Keywords in desktop file should end with ';'

### ISSUE THREAD

**Issue by probonopd** [enzo1982/freac#34]
`org.freac.freac.desktop: error: value "freac" for locale string list key "Keywords" in group "Desktop Entry" does not have a semicolon (';') as trailing character`

Reference:
https://github.com/AppImage/appimage.github.io/pull/1229

**Comment by probonopd** [comment]
Also, the desktop file seems to be there 4x in the repository:

https://github.com/enzo1982/freac/search?q=Desktop+Entry&unscoped_q=Desktop+Entry

**Comment by enzo1982** [comment]
Fixed. Thanks!

The desktop file being there multiple times is intentional. The packaged version is 20181201a and at that point there was no desktop file in the repository. So the file is kept along with the respective packaging scripts in order to have everything in one place.

After the next release, all packages will use the main desktop file in the top-level metadata folder and the additional copies will be gone.

**Comment by probonopd** [comment]
Thank you.
