### ISSUE TITLE
wma encoding error 

### ISSUE THREAD

**Issue by zachaarisd** [enzo1982/freac#361]
Wvery time i use WMA mode  9.2 and try to use a the parameters  from the drop down menu of the codec use format it always then resets into the 8 8 mono CBR 
I prefer to use the 48/44 CBR mode 
even saving the session does not help i9n the configuration menu ...

here is a shot for the reset mode : 
![Στιγμιότυπο οθόνης 2022-08-24 181302](https://user-images.githubusercontent.com/111998722/186456478-46706f79-8b47-4d07-b487-9625a24b52a0.jpg)

**Comment by enzo1982** [comment]
Thank you for reporting this!

The issue only affected the configuration dialog. I.e. the settings you configure in the dialog are effective when converting, but will be reset to the first entry when opening the dialog again.

This is now fixed in the latest [continuous build](https://github.com/enzo1982/freac/releases/tag/continuous).

**Comment by zachaarisd** [comment]
thank you. for the moment its seems to be OK 
this was  the problem from  the 1.1.x versions ie at least 1 year ago

**Comment by enzo1982** [comment]
The fix is now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7). Closing this issue.
