### ISSUE TITLE
[question] where to place custom BOCA scripts if i use flatpak/appimage version?

### ISSUE THREAD

**Issue by axredneck** [enzo1982/freac#38]
Currently i use Fre:ac in form of tar.gz and i have some custom scripts placed in it's "boca" folder. But i want to switch to Flatpak version in order to update Fre:ac easier.

**Comment by enzo1982** [comment]
Using custom codec scripts from a place outside the application package is not currently supported.

For Flatpak it possibly never will be due to the sandbox. Even if scripts could be loaded from the user's .config folder, fre:ac would not be able to run the referenced codecs from inside the Flatpak sandbox.

With AppImages it might be possible as there is no sandbox involved. But support has to be added for this. I put this on my internal list of possible future features.

**Comment by enzo1982** [comment]
With the latest continuous builds you can now put BoCA scripts in `~/.config/freac/boca`. You might need to create the `boca` folder in `~/.config/freac` if it does not exist.

Please check and try if this works for you.

**Comment by axredneck** [comment]
@enzo1982 sadly i can't find so called artifacts anywhere at CI site.

**Comment by enzo1982** [comment]
@axredneck they are right here on GitHub: https://github.com/enzo1982/freac/releases/tag/continuous

**Comment by axredneck** [comment]
Thank You, it works! Did you add it to readme already?
