### ISSUE TITLE
[Wayland, KDE] Can't drag-n-drop files from file managers to fre:ac

### ISSUE THREAD

**Issue by axredneck** [enzo1982/freac#380]
**Describe the bug**
Drag-n-drop of files from different file managers to fre:ac does nothing.

**To Reproduce**
- Log in to Plasma Wayland session
- Run fre:ac
- Drag some mp3 file from any file manager to it

**Expected behavior**
Drag-n-drop should work, like in X11 session.

**System (please complete the following information)**
 - OS: Arch Linux x86_64
 - CPU: Ryzen 5 2600
 - RAM: 16 GB
 - GPU: GeForce GTX 1050

**Additional context**
 - File managers tried: Dolphin, Thunar, Double Commander
 - Fre:ac versions tried:
 - - Appimage from CI as of 2022-10-14
 - - 1.1.6 from AUR

**Comment by enzo1982** [comment]
Which version of KDE are you using? There was a [bug preventing drag & drop between Wayland and Xlib applications in KDE](https://bugs.kde.org/show_bug.cgi?id=437406), but it was supposedly fixed in KDE 5.23.

If you are using KDE 5.23 or later, I will try to reproduce this and investigate whether it's a bug in fre:ac or in KDE.

**Comment by axredneck** [comment]
I use Plasma 5.26

**Comment by enzo1982** [comment]
Thanks! I can now confirm the issue. Drag & drop fails in a Wayland session while it works in an X11 session.

I'll investigate and see what I can do.

**Comment by enzo1982** [comment]
This seems to be KDE's drag & drop implementation being broken.

There appear to be at least two issues:

1. Drag & drop events for Xdnd protocol level 1 and later should contain a time stamp, but the events generated by KDE on Wayland always have a time stamp of 0, even though KDE claims to support at least protocol level 5.
2. Requesting the dropped data using XConvertSelection() fails. The SelectionNotify event generated in response to that call has the property field set to 0 which indicates that no owner for the XdndSelection was found.

The issue is also reproducible with Audacity and probably with other Xlib clients too. So it's not a fre:ac issue.

Please report the issue to the KDE project instead.

**Comment by enzo1982** [comment]
Closing as wont-fix.

If you hear anything back from the KDE project, please comment here.

**Comment by enzo1982** [comment]
Alright, so what I was writing above was based on KDE 5.24. I just did a test with KDE 5.26 and can observe slightly different behavior there.

The two issues I described are still present, but on KDE 5.26, Audacity manages to get some information out of the drag & drop operation. It still does not open the file, but prints an error message including the file name. At a glance, it looks like it's getting the file name with an appended newline character and thus cannot open the file.

The fact that it is able to somehow access the file name at all gives me some hope that I can work around the KDE issues in fre:ac somehow. So I'll continue investigating.

**Comment by enzo1982** [comment]
Reopening this as I have found a work-around.

The second issue (XConvertSelection() failing to find an owner of XdndSelection) only happens when fre:ac returns XdndActionPrivate as the drag & drop action it will take upon dropping files.

The specification allows this and defines the meaning of XdndActionPrivate as follows:

_The special action XdndActionPrivate tells the source that the target will do something that the source doesn't understand and that won't require anything from the source other than a copy of the data._

KDE, however, does not seem to like that...

Returning XdndActionCopy as the action seems to work, though, and fixes that issue.

Maybe this is related to the first issue (the time stamps being missing). In the Wayland context, KDE seems to implement only the most basic things necessary for the Xdnd protocol to work. Time stamps were added in protocol version 1 (the initial version was 0), actions in version 2. So if KDE only implements protocol version 0 from 1998, that explains why time stamps are missing and XdndActionPrivate is not working.

It advertises itself as supporting protocol level 5 in the XdndEnter message, though...

Anyway, I should have an implementation of a work-around ready by tomorrow.

**Comment by enzo1982** [comment]
Please try the latest continuous build. It should fix the issue on KDE 5.26 on Wayland.

Drag & drop still doesn't work on KDE 5.24, but as that also affects other apps and is clearly a KDE issue, I'm not going to investigate that any further.

**Comment by axredneck** [comment]
Thank you, now it works!
