### ISSUE TITLE
Track order in job list not listed consecutive.

### ISSUE THREAD

**Issue by BeneThien** [enzo1982/freac#387]
**Describe the bug**
After adding audio from a remote CD into an empty job list the order of the tracks is not consecutive.

**To Reproduce**
Just add audio from a remote CD with more than 9 tracks.

**Expected behavior**
The tracks should be listed in consecutive order.

**Screenshots**
see screenshot attached
<img width="904" alt="Schermafbeelding 2022-11-09 om 17 45 45" src="https://user-images.githubusercontent.com/117846867/200891387-3282486c-66da-465c-8ea8-0e84ea193f84.png">

**System**
 - OS: [macOS Monterey 12.06.1]
 - CPU: [Intel i9 MacBook Pro 2019 15"]
 - RAM: [16 GB]

**Additional context**
As my MacBook Pro has no CD/DVD driver I add the CD tracks to the empty job list by choosing 'From folder' and click on <select> to then browse to the shared Audio CD. A hackintosh running OS X Snow Leopard 10.6.7 with a shared CD/DVD drive is connected to my local network. I don't know if the problem also occurs when a portable CD/DVD drive is connected to my laptop. Hope this helps.

**Comment by enzo1982** [comment]
When adding files using the _From folder_ command, the order the files appear in the joblist is dictated by the order they appear in the file system.

When adding CD tracks this way, you are actually adding .aiff file representations of the tracks, generated on the fly by the host operating system, so the file name sort order applies.

Unfortunately, the .aiff file names macOS generates for CD tracks don't include a leading 0 in track numbers below 10. The files are named e.g.:

  1 Audio track.aiff
  10 Audio track.aiff
  11 Audio track.aiff
  2 Audio track.aiff
  3 Audio track.aiff
  ...

Because file name sorting applies, the tracks from 10 to 19 come between track 1 and 2. That's a flaw of macOS, not of fre:ac.

You can get the correct sort order in fre:ac by clicking the header of the _Track_ column in the joblist to sort after that column. As fre:ac adds the leading zero to track numbers, this will restore the original CD track order.

**Comment by BeneThien** [comment]
Ok, thanks.

Op wo 9 nov. 2022 23:33 schreef Robert Kausch ***@***.***>:
