### ISSUE TITLE
Sample format trouble

### ISSUE THREAD

**Issue by radorn** [enzo1982/freac#396]
I tried converting a 32-bit floating point WAV to WavPack, and it got converted to 32-bit fixed point. Signal Processing chain is empty and the function disabled altogether, so I expected the format to be preserved.
After that I tried using Signal Processing to force float, and it still produced a 32-bit fixed point WavPack.

**Comment by enzo1982** [comment]
Indeed, that's a bug. fre:ac didn't allow floating point samples when using external encoders.

This was a leftover of when fre:ac didn't have a way to specify the supported input formats for external encoders and was used to prevent failure of encoders that do not support float samples.

This is fixed in the latest continuous build.

**Comment by radorn** [comment]
Thanks for the fix.

**Comment by enzo1982** [comment]
The fix is now included in [fre:ac 1.1.7](https://github.com/enzo1982/freac/releases/tag/v1.1.7). Closing this issue.
