### ISSUE TITLE
Allow setting manually the extension

### ISSUE THREAD

**Issue by Arno500** [enzo1982/freac#40]
**Is your feature request related to a problem? Please describe.**
On Android for some reasons, .opus files are not appearing in GPlay Music. Therefore, I need them to have an .ogg extension.

**Describe the solution you'd like**
When setting a file pattern, I'd like to be able to set an "extension" field. In my specific case, I can remove it and set a fixed text (".ogg").
Another solution would be to allow simply setting the output file name, like any other program.

**Describe alternatives you've considered**
I can rename all my files in batch, but this is slow for nothing. I already made a script to convert all my files, thus specifiying an output file by hands, with an extension of my choice, but for pattern uses this can be problematic.

**Additional context**
You would also need to modify your encoders interfaces to allow them to feed the extension to the main program.

**Comment by enzo1982** [comment]
.ogg never was a valid file extension for Opus files. Opus defined the .opus extension from the beginning with .ogg already being understood to imply Vorbis content at the time.

See here: https://wiki.xiph.org/index.php/MIME_Types_and_File_Extensions

    .ogg applies now for Vorbis I files only

Android 7 to 9 fail to recognize the .opus file extension even though they perfectly support the file type. Changing the file extension to one known to Android will enable playback of such files. It's pure coincidence, though, that this works with .ogg as it also works with .m4a, for example. .ogg remains an invalid file extension for Opus files. This issue was fixed with Android 10.

So I won't add the .ogg extension for Opus files as this would promote using an invalid file extension that is now reserved for Vorbis files only. Especially so as .opus support is already available in Android 10.

If you need to create Opus files that play on Android 7 to 9, please use a batch renamer to change the extension to .ogg after conversion or use a 3rd party player app that supports the .opus extension on the Android device.
