### ISSUE TITLE
CDDB music dB is lame

### ISSUE THREAD

**Issue by jo99jo** [enzo1982/freac#415]
This is an ongoing problem.  There are too many CDs that don't have any info from CDDB.  This lack of info is for common artists.  I've already had to manually add 3 CD's worth of info and I still have 6 additional ones to do!  This is a real PITA because I have to look up the info on the web and then copy the track names from something like Discogs and then paste them into fre:ac one by one.  

At least you could make this a bit easier by allowing a batch input from the clipboard that would fill in all the track names sequentially like EAC can do.

Here are the 6 CD's whose info can't be found and I have to manually enter each.  These are famous musician names, not some obscure artists.

Jack Dejohnette - Special Edition
John McLaughlin - Floating Point
Chick Corea - The Virgil
Avishai Cohen - Cross My Palm With Silver
Wynton Marsalis - Selections from Swinging into the 21st
Nicholas Payton - Dear Louis

**Comment by jo99jo** [comment]
I don't think this is a BUG.  Should be an enhancement request or merged into the musicbrainz comment but I couldn't figure out how to change it from bug.

The main point is that would really like to see input from the clipboard to fill in unknown discs.  EAC allows this and I use the clipboard (sourced from somewhere on the net like Discogs) to fill in the song titles.  EAC also allows for typing/pasting the artist name in the main field at the top of the entry and it will then propagate through the entries on each song title.  With this functionality it isn't too hard to fill in missing CD info.

**Comment by Lee-Carre** [comment]
> CDDB music dB is lame

This is hardly an encouraging start. I must disagree; it's very helpful. Especially given the era of when it originated (hence it being rather simpler than the likes of MusicBrainz, which might be considered the next generation, having learned from the CDDB/FreeDB/GnuDB model).

CDDB/FreeDB/GnuDB isn't part of, or under the control of, Fre:AC (or its developers). Fre:AC simply interacts with it (much as it uses libraries to enable handling of various codecs). Problems with external modules/services/libraries are best directed to the folks who maintain it, not the folks who develop software which ‘merely’ uses it.

Given what you go on to say; it's important to make a distinction between, in this case, the database itself, and the usability of any particular software for contributing data to it. You don't *have* to use Fre:AC to contribute metadata, after all; use whatever you prefer, and then Fre:AC to read that same data (as is the magic of a community project using open standards).

> There are too many CDs that don't have any info from CDDB. This lack of info is for common artists. I've already had to manually add 3 CD's worth of info and I still have 6 additional ones to do! This is a real PITA because I have to look up the info on the web and then copy the track names from something like Discogs and then paste them into fre:ac one by one.

Sigh.

CDDB metadata is a community effort. So, yes, someone has to be a data-input monkey at some point. All existing CD metadata was manually input by someone else (it's not magic). This also includes if you fetched metadata from elsewhere; how did it get in that dataset from which you copied?

Your complaint is better directed to distributors (‘labels’) for failing to add metadata of their releases to public databases, or failing to make it easy to copy+paste from (perhaps due to copyright restrictions/ambiguity) them to community ones.

These principles apply, fundamentally, to most any project.

Compare:
* [OpenStreetMap](//www.openstreetmap.org/) — “my area isn't mapped!” — OSM was actually started in Britain, because of Ordinance Survey (paid for via taxes) being completely unreasonable and otherwise difficult when it came to taxpayers actually using (not just viewing) the data which we had paid for
* [OpenFoodFacts](//world.openfoodfacts.org/) — “my  favourite product isn't included!”; interesting OFF actually addresses the root of the very problem you describe, and invites product manufacturers to contribute data — OFF also makes clear (some of) the problems relating to copyright, and why users can't simply copy data from the manufacturer's website, but have to manually input it from the packaging; so blame the copyright trolls for the draconian anti-sharing regime we're all in

Actually, since I'm moderately familiar with the sordid world of copyright; copy+pasting from elsewhere *might* (this isn't legal advice, I'm not a lawyer, and certainly not *your* lawyer) be a violation of various terms of use/service, which are likely there due to copyright restrictions. As opposed to inputting the data yourself, from what's printed on the liner notes. See above re OSM & OFF and their policies on where data may come from.
Besides, metadata from elsewhere may not be accurate.

Compare; copying a photo means that copyright applies, as does any granted license, and the copyright holder isn't you. Whereas, capturing your own photo; you're the copyright holder, and (ultimately) decide on licensing and such.

Similar with metadata; that which you input yourself, is far less problematic/risky (it can be argued that liner notes are public domain; same as the photos you take in public are yours without needing the permission of a third-party), than that which you've literally copied from elsewhere. Even if you're not acting against the terms of the source (Discogs, or whatever), then you may well be in violation of the terms of the CDDB you're using.

While I'm not saying that this is how things *should* be, but simply how they actually are; copyright infringement, and especially the monstrous DMCA/EUCD, is serious, with non-trivial consequences. This is why everyone (with a clue) is somewhat anal/OCD about avoiding the possibility of being slapped by a copyright troll. Even if they win the case, they're out of pocket on legal fees (lawyers ain't cheap!). The risks are too great. Many cases demonstrate this. Copyright trolls are trigger-happy, and will gladly sue anyone they feel like (even if they're not actually infringing, even if they're a student, and even if the settlement demand is that student's life savings (of $20K); real case. Else, a child's Whinnie The Pooh laptop being seized as evidence, meanwhile the head of RIAA admitting that his own children engage in the very same practises).

Might I suggest that instead of vaguely complaining, you actually help improve the situation. That starts with contributing (unencumbered) data to the database. The above should be enough to point you in the direction of addressing deeper (legal) problems in society. Talk to your elected representative about fixing this mess. Not just copyright, but (software) patents, too. It's a nightmare, which has extensive chilling effects.

> At least you could make this a bit easier by allowing a batch input from the clipboard that would fill in all the track names sequentially like EAC can do.

This is something much more specific, and useful.

So, some considerations on that basic proposal
* one would have to account for variations in the formatting/structure of the text on the clipboard (and if it is, indeed, actually plain text, rather than RTF, HTML, or anything other than literal characters
* as mentioned, there are likely entirely justified reasons for avoiding copyright penalties, that mass-import isn't facilitated; especially if you're supposed to be manually typing it in from the liner notes, anyway
* it would seem to me better to use a different tool, dedicated to editing CDDB metadata, with features for the type of batch handling you describe; adding those same features to every audio extraction tool is inefficient, and will just add bloat — lots of engineering principles behind this
* as per other tickets (#36), Fre:AC developers are intending (when time permits) to implement the ability for Fre:AC to query the MusicBrainz API/DB — in which case, since the MB scene has a variety of tools, you may be better off contributing there, using whatever software (that speaks the syntax of MB's API) best suits you — though, again, legalities apply, especially if you're wanting to copy from elsewhere
* as mentioned above, you could use EAC if that's what you prefer. Once the metadata is in the DB, then you can use it in Fre:AC — what's the actual problem, here?

> Here are the 6 CD[]s whose info can't be found and I have to manually enter each. These are famous musician names, not some obscure artists.

What's anyone else supposed to do with that? Even if you *had* included the track name info, then you're still expecting others to input it for you.

Just type it in, already, since you seem to have possession of that info (included with the copy of the audio). You claim that the metadata can't be found. Um, it's likely right in front of you, in the liner notes. If it's not in a public DB; well, then add it like a helpful netizen and community-member. What's the problem? It need only be entered once, for everyone to benefit.
This, ironically, is (one of the reasons) why the likes of MusicBrainz counts the edits made by users, espcially how many new additions they've added; reputation/status. Be the cool kid on the block, which adds a whole bunch of otherwise missing data. Especially for, as you claim, popular albums.

A simple, easy, but cheap retort to your “… famous musician names, not some obscure artists.”. Well, I've never heard of them. Yes, I'm aware of how that's logically fallacious, and that you could also retort with an ad hominem about how I'm uncultured.
Though, this is why I listen to [Radio Paradie](//www.radioparadise.com/); to hear music that I've never heard before.
Just because *you* like them, doesn't mean everyone else is familiar. Evidently not enough to have added them to the database.

It could also be that you might have a rare pressing, which has a rare DiscID, but which actually matches a more common one which is already added. This is something which MusicBrainz handles more gracefully than the CDDB model. Again, contribute the data and be done with it. Others (including myself) will appreciate it.

> I don't think this is a BUG.

Yet, “jo99jo added the `bug` label”.

Choose the right template, when opening a ticket.

> Should be an enhancement request

Yes, and made clear as such. Starting with fixing the off-putting title to something descriptive.

Seriously, read [How to Ask Questions the Smart Way](/selfteaching/How-To-Ask-Questions-The-Smart-Way/blob/master/How-To-Ask-Questions-The-Smart-Way.md) (to elicit the kind of (helpful) answers you really want). Including the linked How to Reports Bugs Effectively. General whining absolutely doesn't qualify.

> or merged into the musicbrainz comment

There's no merging (as far as I'm aware), but they'll be cross-linked now that I've mentioned that ticket, here. Perhaps you should've commented on #36, instead. Though, CDDB and possible MusicBrainz API, are separate things in terms of implementation, so a separate ticket isn't inherently wrong in this case. However, this ticket is, at best, about usability of inputting data for CDDB submission, rather than about the CDDB itself or Fre:AC's API implementation.

This may sound pedantic to a non-tech, but the details matter, and in order to be helpful to developers, then precision (as opposed to verbosity) is necessary. It took a while  for me to even determine what problem you were actually complaining about, for starters. You assumed much, instead of describing the facts. Read the above-linked guides (about asking smart questions and reporting bugs).

> I couldn't figure out how to change it from bug.

Since you're the author of this ticket, there are various edit buttons dotted around, to fix the title, your tags/labels, and the OP description. I suggest you use all of them. You'll need to authenticate to GitHub (‘log in’) using the same account as the one you opened the ticket with. GitHub also has extensive documentation, which I suggest you consult.

> The main point is that would really like to see input from the clipboard to fill in unknown discs. EAC allows this and I use the clipboard (sourced from somewhere on the net like Discogs) to fill in the song titles.

The tone of this is far less heated. Would've been better as your OP. But, alas.

I'm not familiar with EAC (never used it, but know what it is), so I can only respond in general terms.

Again, if you prefer EAC, then use it.

However, I suspect that the problem, here, might be that EAC is only editing local metadata, rather than contributing said metadata back to CDDB (GnuDB, or whatever we're using now). If so, then **that** is the source of the problem. Rais this with the EAC devs, to have it fixed, so that everyone benefits.

> EAC also allows for typing/pasting the artist name in the main field at the top of the entry and it will then propagate through the entries on each song title. With this functionality it isn't too hard to fill in missing CD info.

Depending on exactly what you mean, then Fre:AC already enables this. You want the `Tags` tab, and select the `Album` sub-tab.

However, if you do mean in the CDDB submission UI; as far as I'm aware, if the album has a single artist, then this is indeed propagated to all the tracks by default. You don't even have to retype/copy+paste it per-track.

But, again, back to what I said about copyright complications (which might be why EAC is making only local changes, not uploading to the CDDB, simply to avoid the possibility; but then complaining about the metadata **not** being in the DB, is hardly valid).

It's also not a goal of Fre:AC to achieve parity with any other tool. Fre:AC is going its own way. If you want EAC, or a clone of EAC, then you know where to look.

Unless I'm unclear on what you do mean (likely; difficult to parse a vague description).

Keep in mind that it's unreasonable (for many reasons) to expect Fre:AC to be all things to all users. What makes Fre:AC good at what it does, is that it keeps to a relatively narrow scope.

If you're wanting to do something unusual/complicated, then other tools are likely better suited. [Picard](//picard.musicbrainz.org/) has non-trivial metadata handling, renaming & reorganisation features, and is designed for mass-editing (eg an entire library, let alone a whole album).

---

More generally, hostile/accusatory whining isn't the way to encourage developers to even read your ticket, let alone address it, or implement changes.

enzo1982 volunteers his time to develop Fre:AC. Have you made a donation? Don't treat it, or him, as some corporation with a customer service department (who will hand-hold you because you're giving them money). Regardless, figure out how to be helpful, if you want anything other than to be ignored. This isn't the place for shit-posting, only serious no nonsense matters. A reality-check, if you please.

**Comment by jo99jo** [comment]
Whew.  Centuries ago Shakespeare wrote "brevity is the soul of wit",  Were he alive today, I'm certain he would extend that statement to rambling, unfocused streams of consciousness, such as what you write above.

Whatever, I switched to EAC and signed up for a GD3 lifetime license @ $7.99.  Problem solved.

**Comment by Lee-Carre** [comment]
> Centuries ago Shakespeare wrote "brevity is the soul of wit", Were he alive today, I'm certain he would extend that statement to rambling, unfocused streams of consciousness, such as what you write above.

I wasn't aiming for wit (I tend toward sarcasm), but informative explanation and a little persective. You also seem to assume that you were my intended audience for the exasperated tone; nope, it's not all about you. Since careful explanation is clearly wasted on respondents, here, instead I'll quote & cite others (unfortunately, I don't recall Will having much or anything to say on technology (though, plenty about human nature); I'd have to consult the hefty *Complete Works* of his, sitting on my bookshelf).

If you prefer succinct & pithy; I can do that …; seems that all you've got is more of the same ad-hominems, and projection. Listen to Jordan Peterson, and start taking some responsibility (clean your room!). Criticism about verbose ramblings, is rich coming from someone who whined for several paragraphs before actually getting to any relevant & meaningful point. Grow up. You asked for help (even if poorly, by posting); if you actually don't want it, then why are you here? (No, that's rhetorical, for you to self-reflect upon.)

“The multiplying villainies of nature do swarm upon him.”

Now, for scathing wit. I did mention quoting & citing others. Let's start with [Rick Moen](http://www.linuxmafia.com/~rick/):
> *Economy of expression* is a good thing. […]

Also Rick Moen (from his [security snake-oil essay](http://www.linuxmafia.com/faq/Essays/security-snake-oil.html)):
> Now, all of the above took a fair amount of time to research and explain, which is part of the problem. This sort of dopey [CDDB is lame] line that [jo99jo] puts out takes him almost no time to compose, but takes serious time to debunk.

I'm rather confident that Moen would concur with me, here, too.

[Moen's Law of Clueless Newbiehood](http://www.linuxmafia.com/~rick/lexicon.html#moenslaws-outlook) seems entirely apt (in nature/principle, rather than the specifics):
> "The whiniest new users, and especially the ones who claim your sole purpose in life should be to help them, always say that using MS Outlook (or Outlook Express)."
> 
> I first noticed this correlation on Linux mailing lists and newsgroups. (The point, in part, is the irony inherent in demandingly seeking intensive personal assistance on a public Linux forum, using a particularly notorious Microsoft application.)

Then there's the whole [Crybaby section of his FAQ](http://www.linuxmafia.com/~rick/faq/crybaby.html). Several of the entries come to mind.

Don't know who Rick Moen is? That says more about you, than others, in this context/realm.

> I switched to EAC and signed up for a GD3 lifetime license @ $7.99. Problem solved.

Hardly. Maybe the symptoms. If you were interested in solving problems, then your OP would've been much more to the point, sans whining and SIGN language.

If you care more about convenience, than liberty, then GitHub probably isn't the place for you. Paid hand-holding seems much closer to what you seek.
Don't forget to donate to GnuDB, since you're clearly using their service, possibly also MusicBrainz, too.
Can't (reasonably) demand five star service, while paying nothing.

---

Thanks for playing; better luck next time. Don't let the door hit you in the arse, on the way out. {Slams it, firmly, closed.}

**Comment by jo99jo** [comment]
I truly feel sorry for any family you may have that have to live with you.

**Comment by Lee-Carre** [comment]
Separately to UI objctions; avoid them entirely. Fre:AC saved CDDB metadata to local files (on Windows, you can find them by navigating to `%AppData%\freac\cddb`).

1. Ensure that Fre:AC has queried the CDDB for the disc you wish to edit, or otherwise that it has placed a local file (can be triggered by making any minor edit to the metadata (for submission to CDDB) and saving the changes for later)
2. Ensure that Fre:AC isn't running
3. Find the file for the disc in question (based on the DiscID)
4. edit that file however you wish with whatever text-manipulation tools (eg, an [editor](//www.gnu.org/software/emacs/)) you wish/like/prefer.
5. Once happy with your changes, save, and ensure that your editor/tools aren't gonna mess with the file again
6. Launch Fre:AC
7. have Fre:AC upload/submit the modified metadata for the disc

**Comment by Lee-Carre** [comment]
I was recently reminded that CDDB submission fields are auto-populated from the values used in the tag editor fields (which itself offers some degree of batch-editing, such as applying album info to every track).

But, again, Fre:AC isn't (primarily) about tag-editing.
