### ISSUE TITLE
Doesn't auto add the music joblist

### ISSUE THREAD

**Issue by jo99jo** [enzo1982/freac#416]
fre:ac never adds the joblist music on its own when I insert a disc, like EAC does.  I always have to click the File->Add->Audio CD Contents two and sometimes three times before the add is processed and the list is shown.  This is annoying.

**Comment by enzo1982** [comment]
fre:ac should automatically add CD tracks to the joblist by default when inserting a CD. Please check if the corresponding option is enabled in the ripper settings.

I have noticed issues with this functionality on older versions of Windows in the past. On some systems, the disc insert broadcast message never seems to reach fre:ac or other applications, so disc inserts will not be detected. On those systems, this also affects other applications like EAC, though.

I don't currently have any system where I can reproduce issues with disc insert notifications.

By the way, you can just click the second toolbar button to add CD tracks. No need to click through the menu.

**Comment by jo99jo** [comment]
> Please check if the corresponding option is enabled in the ripper settings.

What option are you referring to? 

Most of the time I do have to use the 2nd toolbar button AND I always have to click it twice.  The first time I click, nothing happens.

I am running Win10 completely up to date.

**Comment by enzo1982** [comment]
> What option are you referring to?

This one:

![ripper](https://user-images.githubusercontent.com/7796713/211176948-dd630b61-391f-4b68-ad0e-78aeb8e81191.png)

However, I was able to partially reproduce this issue here today, so I think you may experience the problem even with the option enabled.

I have two CD drives in my main system. When inserting a disc in the first one, Windows always sends a WM_DEVICECHANGE message to notify the program about the change. However, when inserting a disc in the second drive, Windows does not send a message most of the time. Therefore, fre:ac will not know about the newly inserted disc.

I have found claims that trying to access the drive will make Windows send the message and this may make it possible to work around the issue. I'll see if I can figure out a solution in the next few days.

> Most of the time I do have to use the 2nd toolbar button AND I always have to click it twice. The first time I click, nothing happens.

That should not be necessary and I cannot reproduce that issue here. If you press the button while the drive is still loading the disc, nothing will happen. But after the drive has finished loading the disc (usually after 10-15 seconds), one click on the button should be enough to add the tracks to the joblist.

**Comment by enzo1982** [comment]
I implemented an additional way to detect disc inserts and removals that engages when no WM_DEVICECHANGE message is sent.

Please try the latest [continuous build](https://github.com/enzo1982/freac/releases/continuous) and check if that fixes the issue.

**Comment by jo99jo** [comment]
> I implemented an additional way to detect disc inserts and removals that engages when no WM_DEVICECHANGE message is sent.
> 
> Please try the latest [continuous build](https://github.com/enzo1982/freac/releases/continuous) and check if that fixes the issue.

OK, the addition seems to work as long as freac is open when I insert a disc.  However, if the disc is already in the reader AND then I start freac, the auto read does not work.

**Comment by enzo1982** [comment]
> However, if the disc is already in the reader AND then I start freac, the auto read does not work.

It's not supposed to. fre:ac is a file converter in the first place, so a disc that happens to be in the drive when it starts up is not automatically added to the joblist.

I considered adding an option for this, but this would raise additional questions and possibly cause issues. For example, what happens when multiple drives are connected and contain audio discs? Or what happens when automatic ripping after inserting discs is enabled?

Not loading CDs at startup seems to be the option causing less friction than the other way around. When you start the program after inserting a CD you want to rip, you have to click a button to add the tracks. In my opinion that's better than having to clear the joblist every time you start fre:ac to convert some files just because you have a CD in the drive.

So this is by design and I don't plan to change it.

**Comment by jo99jo** [comment]
OK, wasn't sure if it was a feature or a flaw.
