### ISSUE TITLE
Long m4b files show corrupt time signature in iTunes

### ISSUE THREAD

**Issue by Jewdave** [enzo1982/freac#48]
I have not been able to identify the exact duration, but it seems that when I combine multiple files into a single m4b and the length of the output is somewhere over 12-18 hours it will show 200+ hours in length when imported into iTunes. I'm testing to try to find the point it breaks at.

**Comment by Jewdave** [comment]
It doesn't seem to be consistent. Attaching images of 2 examples where I'm encoding multiple mp3s to a single m4b and this occurs. The second one started showing an incorrect length in file explorer as well as iTunes once I got beyond 28hrs.
![Test 1 1](https://user-images.githubusercontent.com/2205183/67628988-7d4ad980-f845-11e9-9963-d4edc998c667.jpg)
![Test 1 2](https://user-images.githubusercontent.com/2205183/67628989-7d4ad980-f845-11e9-879d-c8cfbb775ea0.jpg)
![Test 2 1](https://user-images.githubusercontent.com/2205183/67628990-7d4ad980-f845-11e9-953b-1355a3ddf55c.jpg)
![Test 2 2](https://user-images.githubusercontent.com/2205183/67628991-7d4ad980-f845-11e9-9a56-6013d484a59d.jpg)

**Comment by enzo1982** [comment]
Thank you for reporting this!

The main issue was fre:ac counting the number of samples in a 32 bit value and was already fixed in the source code with commit enzo1982/BoCA@41c9428.

There were, however, several more issues adding to the confusion about very long MP4 files, now fixed with commits enzo1982/BoCA@5a67572 and enzo1982/BoCA@ec2515b.

The first one creates MP4 files with 64 bit size and duration fields when the length approaches the 32 bit limit. The second fixes handling of files with 32 bit duration fields that actually have a duration not fitting in a 32 bit value.

Together, this should greatly improve interoperability with other software when dealing with very long MP4 files.

I compiled a build for you to try these changes: [freac-1.1-alpha-20191027-windows-x64.zip](https://github.com/enzo1982/freac/files/3775819/freac-1.1-alpha-20191027-windows-x64.zip)

Please report back if this fixes the issue.

**Comment by Jewdave** [comment]
Seems to be fixed in iTunes, but still seeing a different time reported in Explorer and VLC.

**Comment by enzo1982** [comment]
When using the Core Audio encoder (the one also used in iTunes), files will still have 32 bit duration fields. There does not seem to be a way to make this encoder create files with a 64 bit duration. Long files created with iTunes seem to have the same issue.

I'll look into the option to use the Core Audio encoder in combination with the MP4v2 library for very long files. That's the library already used with the FAAC and FDK-AAC encoders and is able to write 64 bit duration. This will take a while though.

**Comment by Jewdave** [comment]
Sounds good. I have been just splitting longer mp3 combines into less then 10hr chunks and that has been working in the meantime.  Thanks for looking into it, and thanks for an awesome piece of software!

**Comment by enzo1982** [comment]
Here's another preview build: [freac-1.1-alpha-20191103-windows-x64.zip](https://github.com/enzo1982/freac/files/3801540/freac-1.1-alpha-20191103-windows-x64.zip)

This should fix the issue with long MP4 files created with Core Audio. It works by updating the duration parameters to the correct 64 bit values after Core Audio is done with the files.

This version also fixes some other issues with large files I found while working on this.

Would be great if you could have a look at it!

**Comment by Jewdave** [comment]
I have tested with a few different audiobooks, one of which was made of 73 individual mp3s and a combined length of 33 hours and it works perfectly in VLC, iTunes, and iOS. I'll continue with some more files that caused issues, but I think you may have squashed it!

**Comment by enzo1982** [comment]
Great! Thanks for reporting back!

Please reopen this ticket if you find any issues processing your other files.
