### ISSUE TITLE
Application crash every time when I select "Options > General settings"...

### ISSUE THREAD

**Issue by Divzed** [enzo1982/freac#538]
**Describe the bug**
The application crashes and closes itself when I select "Options > General settings..." or "Options > Configure signal processing...".

**To Reproduce**
1. Go to 'Options'
2. Click on 'General settings...' or 'Configure signal processing...'
3. Windows Event Log:
`Faulting application name: freac.exe, version: 1.1.7.5891, time stamp: 0x6404cf34
Faulting module name: boca_encoder_wma.1.0.dll, version: 0.0.0.0, time stamp: 0x6404c46a
Exception code: 0xc0000005
Fault offset: 0x0000000000001f92
Faulting process id: 0x1158
Faulting application start time: 0x01d9f0abfa4a5202
Faulting application path: C:\Program Files\freac\freac.exe
Faulting module path: C:\Program Files\freac\boca\boca_encoder_wma.1.0.dll
Report Id: 74f6563f-50f0-4039-94ea-e028d19a67b5
Faulting package full name: 
Faulting package-relative application ID: `

**Expected behavior**
Not to crash application.

**System (please complete the following information)**
 - OS: [Win 10 19044.1288 LTSC CUSTOM MOD]
 - CPU: [i5 2400]
 - RAM: [4 GB]
 - Environment: [VirtualBox VM]

Does FRE:AC have any system component dependencies (Internet Explorer/WMP/Windows Error Reporting)?
I ran it in VM original Win 11 22H2 & original Win 10 19044.1288 LTSC.
It worked flawlessly, so it seems like fre:ac relies on some system components that has been removed from my custom windows mod.
Can I know which ones? This is the reason why it crashes when attempting to enter "General settings" page.
There is no documentation about it. Any other audio converting software doesn't have such issues.

**Comment by rileyg98** [comment]
Interesting. I'm having a near identical issue. Are you able to import files? I am having a crash on that as well as settings. Across UWP, installed and portable binary. 

For reference, my system is as follows:
OS: Win11 22H2 (22621.2134 build)
CPU: AMD Ryzen Threadripper 3970X
RAM: 256GB
Environment: Hyper-V, can be more specific

I don't get the event log detailing the faulting module, just a WER info and a "Application Hang".
"The program freac.exe version 1.1.7.5891 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel."

The WER info was: 
Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: freac.exe
P2: 1.1.7.5891
P3: 6404cf34
P4: d3dd
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10:

**Comment by Divzed** [comment]
> Interesting. I'm having a near identical issue. Are you able to import files? File imports just silently fail for me. All of this is across UWP, installed and portable binary.

I can import files without issues on modified OS & original OS (Win10/Win11), only General Settings panel is crashing on modified OS when trying to open it.
I even fresh installed my custom OS again in VM and installed Fre:AC alone, now this additional memory error appears when trying to open General Settings panel.
![123](https://github.com/enzo1982/freac/assets/104203796/c5bb1e54-4a89-49fb-980a-53a91e7bf0eb)

**Comment by Divzed** [comment]
I found the issue. Fre:AC is dependent on Windows Media Player component.
Now I retained WMP in my own OS modification and no more errors/crashes.
Question is, why would anyone in current year rely on Windows Media Player in software development?
WMP is basically deprecated & might be even completely removed in upcoming Windows 12+.
