### ISSUE TITLE
"delete origional files" option is not checked when switching to another profile

### ISSUE THREAD

**Issue by BodoTh** [enzo1982/freac#591]
I have got two profiles I am toggling between via "Options" -> Active Configuration
Both profiles have different settings for this encoding option: "delete original files"

When switching between the profiles the above option is not changed.
When switching to the other profile and restarting the app the option is changed. So it is only loaded on program start but not on profile change!

This means: switching does not set this option. Loading the profile at program start does. This inconsistency is hard to detect but still problematic.

how to reproduce:
Create two profiles with different settings.
switch to the other profile
start encoding and you will see that the option is not active

**Comment by enzo1982** [comment]
Thank you for reporting this! This is now fixed in the latest [continuous build](https://github.com/enzo1982/freac/releases/tag/continuous).

This actually affected the _Shutdown after encoding_ option as well and there was a related issue causing CD ripping automation options to become greyed out after switching the configuration. This is now fixed too.
