### ISSUE TITLE
Inability to launch fre:ac

### ISSUE THREAD

**Issue by Kugumin** [enzo1982/freac#69]
**Describe the bug**
The "bug" seems to be an some kind of user-side issue as last time I used fre:ac to convert music it worked. It was **fre:ac v1.1 α 20190423**.  After a while and some Windows 10 updates it doesn't launch at all now. Tried new version of fre:ac (**fre:ac v1.1 Beta 1**) - same, nothing happens.

**To Reproduce**
1. Try to launch fre:ac app
2. See nothing happening

**System**
 - OS: Windows 10 Pro (Version 1903)
 - CPU: Intel Core i5-2450m
 - RAM: 6 GB

**Comment by enzo1982** [comment]
Thank you for reporting this and sorry for responding only now!

So the 20190423 worked initially, but stopped working at some point before the 1.1 beta 1 update already?

I think that some configuration setting might be causing trouble and prevent fre:ac from starting. Please try if removing your `freac.xml` configuration file helps fix the issue (but please make a backup of it so you can attach it here for further analysis).

The `freac.xml` file can be found either in the fre:ac program folder (where freac.exe is) or in your user profile - usually `C:\Users\<your user name>\AppData\Roaming\freac`.

**Comment by Kugumin** [comment]
> So the 20190423 worked initially, but stopped working at some point before the 1.1 beta 1 update already?

Yes, it did work, but for some reason stopped working at all
Also
I removed that configuration file you told to - nothing changed. Still just nothing happens when I am trying to launch the app

**Comment by Kugumin** [comment]
So... Any ideas what could be the issue?

**Comment by enzo1982** [comment]
Sorry for getting back to you only now! I was quite busy with the previous beta releases.

Could you please look for crash logs appearing in the _Windows Event Viewer_ after trying to start fre:ac? These would appear under _Windows Logs->Application_ and have the _Source_ field set to _Application Error_.

It should look like in the below screenshot. If you find such events, I will need the information from the text box to further analyze the issue.

![crashlog](https://user-images.githubusercontent.com/7796713/72993623-fb436000-3df5-11ea-8458-c8978faae8ee.png)

**Comment by Kugumin** [comment]
@enzo1982, yep, it's here. You can check below

Faulting application name: freac.exe, version: 1.1.0.5059, time stamp: 0x5e1b5e8f
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x2290
Faulting application start time: 0x01d5d245083acd89
Faulting application path: C:\Users\Kugumin\Desktop\freac\freac.exe
Faulting module path: unknown
Report Id: ca70f668-7916-4eb7-96cb-b60dc40b7e09
Faulting package full name: 
Faulting package-relative application ID: 

![image](https://user-images.githubusercontent.com/42800753/73032938-2f943c00-3e49-11ea-99fe-6f19867f0e08.png)

**Comment by enzo1982** [comment]
Thank you for providing the error data. An _unknown_ module with a zero offset address usually means that the program tried to make a function call to a library that was not correctly loaded.

I think this can only really happen with fre:ac when scanning and loading the components in the `boca` folder. It should not be an issue though, unless you copied the new version of fre:ac over an existing installation of an alpha release. Did you do that?

In any case, could you try removing all the `boca_*.dll` files from the `boca` folder and then starting fre:ac? That's all .dll files there except for `boca.dll` itself. fre:ac will not be very useful without these components, but this would confirm if one of the components is causing the issue here.

Then, in a second step, please re-add all the .dll files one by one to try and see which one causes fre:ac to not start. That information would be very helpful.

**Comment by Kugumin** [comment]
> I think this can only really happen with fre:ac when scanning and loading the components in the boca folder. It should not be an issue though, unless you copied the new version of fre:ac over an existing installation of an alpha release. Did you do that?

Yes, I did like that, but also I tried with downloading fre:ac 1.1 Beta 2 .zip and trying to launch it too with both whole package and removing .dll files you just told me. Nothing happens, same "no error" thing

Info about errors:

Faulting application name: freac.exe, version: 1.1.0.5059, time stamp: 0x5e1b5e8f
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x2804
Faulting application start time: 0x01d5d3a4bd6fc86d
Faulting application path: C:\Users\Kugumin\Desktop\freac-1.1-beta2-x64\freac.exe
Faulting module path: unknown
Report Id: 2bb0c08d-91fc-4f49-bd7f-5ad50ac08c3f
Faulting package full name: 
Faulting package-relative application ID: 

![image](https://user-images.githubusercontent.com/42800753/73124923-ad6f5900-3fa9-11ea-9700-d901ddefe854.png)

And maybe this could be helpful

Fault bucket 1496935341994895016, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: freac.exe
P2: 1.1.0.5059
P3: 5e1b5e8f
P4: StackHash_ac46
P5: 0.0.0.0
P6: 00000000
P7: PCH_7D_FROM_ntdll+0x000000000009CC14
P8: c0000005
P9: 0000000000000008
P10: 

![image](https://user-images.githubusercontent.com/42800753/73124938-d09a0880-3fa9-11ea-8b6e-8c4affcbf995.png)

**Comment by enzo1982** [comment]
OK, it's strange that it doesn't start even without the extra components. I don't really have an idea what might be causing this yet.

Did you try the 32 bit version as well? Does it have the same issue?

And can you run the translator.exe from the zip package? Or does it also not start?

**Comment by Kugumin** [comment]
Tried 32 bit one freac, it doesn't start either

`translator.exe` both from 32 and 64 packages starts without any issues

**Comment by enzo1982** [comment]
I think I have found the cause of this issue - by coincidence...

Another user [reported being unable to load certain files with fre:ac 1.0.32](https://github.com/enzo1982/freac/issues/74), but then quickly closed the ticket reporting that it was due the "Beta UTF-8" setting enabled on his system. I didn't know about such a setting on Windows and did some investigation. And yes, Microsoft added a UTF-8 mode that can be enabled in the region settings and causes some legacy APIs to use an UTF-8 codepage.

Then of course I wanted to try it and guess what - fre:ac 1.1 beta does not start when this is enabled. So I think your issue is due to this setting too.

Here's some more about this setting: https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do

Please try if fre:ac does run again when you disable it. I'll try and make the next beta compatible with this.

**Comment by enzo1982** [comment]
The root cause of this is libiconv, which is used optionally by fre:ac to provide better international text support, not recognizing the codepage 65001 which Microsoft uses to mean UTF-8.

I will have a fix for this in the repository later today and the upcoming beta 3 will have it too, of course.

You should be able to run fre:ac 1.1 while this Windows setting is enabled after deleting the iconv.dll from the fre:ac folder.

**Comment by Kugumin** [comment]
FINALLY, IT'S WORKING, THANKS YOU SO MUCH!
![image](https://user-images.githubusercontent.com/42800753/73527062-10824500-441b-11ea-8b51-a8ef12dfbe21.png)
