### ISSUE TITLE
Problem with Ogg Vorbis ...

### ISSUE THREAD

**Issue by ObezyankaNol** [enzo1982/freac#70]
**Describe the bug**
When setting up the Ogg Vorbis Encoder, when choosing ABR and the included options, the minimum and maximum bitrate, when encoding, an audio file with strong distortions is obtained.

**System (please complete the following information)**
 - OS: [Microsoft Windows 10 Home]
 - CPU: [AMD A8-4500M]
 - RAM: [6 GB]

**Comment by enzo1982** [comment]
Thank you for reporting this!

When setting the minimum and maximum bitrates, they got passed to the Vorbis encoder the wrong way around. I.e. setting the minimum to 32 kbps would actually make the encoder try to limit the maximum bitrate to 32 kbps.

This is fixed with commit enzo1982/BoCA@d05ef81. The fix will be in fre:ac 1.1 beta 2.

To work around this issue, either don't set the minimum and maximum bitrate options or switch the values, e.g. minimum 320 kbps, maximum 32 kbps.

**Comment by enzo1982** [comment]
I now have a preview version ready for you with the fix: [freac-1.1-beta1a-windows-x64.zip](https://github.com/enzo1982/freac/files/4007175/freac-1.1-beta1a-windows-x64.zip)

**Comment by ObezyankaNol** [comment]
I did not expect to fix it so quickly. Now everything works as it should. Thank you.

**Comment by enzo1982** [comment]
Great! Thanks for reporting back!
