### ISSUE TITLE
can't load files Windows 10

### ISSUE THREAD

**Issue by dvirtz** [enzo1982/freac#74]
**Describe the bug**
Using version 1.0.32, I'm trying to load mp3 and mp4 files and I get an `Unknown file type` error.
It did work for me in the past. Seems like some windows update killed it.
I tried going back to 1.0.31 and loading different files but it's the same.

**To Reproduce**
1. Load an mp4 file
3. See error

**Expected behavior**
Show the file in the joblist.

**System (please complete the following information)**
 - OS: Windows 10 Home 1903
 - CPU: Intel Core i7 7500U
 - RAM: 12 GB

**Comment by dvirtz** [comment]
seems like it's caused by my locale settings having UTF-8 beta support on. I've switched it off and the problem's gone.

**Comment by enzo1982** [comment]
Hi, I was just about to answer and wanted to suggest trying fre:ac 1.1 beta. But now your new comment has made me curious.

I looked into Windows 10's region settings and there is this setting: "Beta: Use Unicode UTF-8 for worldwide language support" I guess that's the setting you had enabled?

I'll look into this. Didn't know about this until now. I'll see if I can find a way to make fre:ac work with it.

**Comment by dvirtz** [comment]
Yes, that's the setting.
I tried 1.1 but ran into https://github.com/enzo1982/freac/issues/69

**Comment by enzo1982** [comment]
Thank you for confirming!

I found what's causing this and will have a fix ready soon. There will also be a fre:ac 1.0.33 coming soon (which was already planned before) that will get the fix.

The issue is due to libiconv not recognizing the 65001 codepage, which Microsoft uses to mean UTF-8. Deleting the iconv.dll from the fre:ac folder should make the issues go away (libiconv is used optionally to improve international text support, but is not strictly necessary to run fre:ac).

**Comment by dvirtz** [comment]
Removing libiconv indeed helps.
Thanks for looking into it.
