### ISSUE TITLE
missing tags when encoding ALAC/M4A to AAC/M4A

### ISSUE THREAD

**Issue by gdsa32** [enzo1982/freac#9]
I am using fre:ac v1.1 alpha 20180306 32bit, on Windows 10 64bit.
I have found an issue that causes some of the converted tracks to have missing tags.

Here are the conditions necessary to trigger the issue:
- Parallel processing must be enabled in Settings > Resources. The more cores enabled, the more tracks with missing tags we'll have.
- Input format/extension must be ALAC/M4A (Apple Lossless).
- Output format/extension must be AAC/M4A using Core Audio Encoder.
- Job list must have enough tracks to keep the system busy for some time. Say, at least 2x the number of available cores.

With all these requisites met, the resulting converted tracks will have a mix of tagged and untagged track.
I've made some non exhaustive tests using other combinations of input and output formats, but I wasn't able to reproduce the issue. Only ALAC --> AAC seems problematic.

I attached some screenshots of File Explorer showing both the original input files, as well as those converted to AAC/M4A and to FLAC. Note that FLAC is correctly tagged.

![freac-error-input](https://user-images.githubusercontent.com/39100541/39776554-98c45b06-52d7-11e8-9700-d050a2147ccb.png)
![freac-error-output](https://user-images.githubusercontent.com/39100541/39776555-98e0e26c-52d7-11e8-926c-fb1bff64f602.png)

**Comment by enzo1982** [comment]
Looks like it might be a thread-safety issue in either fre:ac's Core Audio adapter, the MP4 tagging component or the MP4v2 library used to handle those files. I'll see if I can reproduce this and track it down.

**Comment by enzo1982** [comment]
I can reproduce the issue now, but it remains mysterious.

Somehow, when running in multi-threaded mode and the input comes from an external decoder, the call to Core Audio's `AudioFileClose` function does not actually close the file. It remains locked and thus no tags can be written. The file will also remain in the temp folder as it cannot be removed while locked. `AudioFileClose` does not return an error, though, but claims the file had been closed properly.

This happens when any external decoder is active. It's not necessary for the input files to be in ALAC format - they can also be in MusePack, WavPack, TAK or OptimFROG for example.

I have no idea why this happens. The decoder and encoder have no direct connection and operate on different files.

I will test with different versions of Windows to rule out a bug in recent versions of Windows 10. Do you have the Windows 10 1803 update installed already?

**Comment by enzo1982** [comment]
So, I spent some time analyzing this issue today and have found the cause of it along with a possible solution.

After some really tough debugging and mind twisting, it turned out that Core Audio is opening files with handle inheritance turned on when using the AudioFileCreateWithURL API call. Handle inheritance means that sub-processes created by an application will automatically duplicate any such handle and acquire a lock on the resource represented by it.

In this case, fre:ac is creating sub-processes to decode the ALAC files and due to handle inheritance, each decoder sub-process will get a handle to any file opened through Core Audio up to that point, locking it until that sub-process exits. fre:ac then in turn cannot modify those files after Core Audio is done with them until the decoder processes finished and closed the files as well.

That behavior of Core Audio is extremely unfortunate, especially as handle inheritance is turned off by default on Windows, so they must be turning it on deliberately. I can't think of any good reason for this in this case, though.

Fortunately, there is a solution. It is not to rely on Core Audio's file handling, but using AudioFileInitializeWithCallbacks to do our own file I/O with Core Audio calling our custom functions for reading, writing etc. when it needs to operate on a file. The files can then be opened with handle inheritance turned off and the issue should go away.

I'll need a few days to implement this solution and will report back.

**Comment by gdsa32** [comment]
Good to know you could find the cause. Here's waiting for a new alpha with the solution.

**Comment by enzo1982** [comment]
This is fixed now in enzo1982/BoCA@adfeca9.

Here's a build of fre:ac with the changes for you to test: [freac-1.1-alpha-20180610-windows.zip](https://github.com/enzo1982/freac/files/2088031/freac-1.1-alpha-20180610-windows.zip)

Please close this issue if this fixes it for you.

**Comment by gdsa32** [comment]
I just tested this new build and I can confirm the issue has been resolved. Tags are now written correctly with multi-processing enable.
Thanks.
